### ISSUE TITLE
custom_error helper not send response code from post lua scripts

### ISSUE THREAD

**Issue by mathewsheets** [krakendio/krakend-ce#266]
The custom_error is only sending response code on pre lua scripts and not post lua scripts.

```
{
  "version": 2,
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level": "DEBUG",
      "prefix": "[api-gateway]",
      "syslog": true,
      "stdout": true,
      "format": "default"
    }
  },
  "timeout": "60000ms",
  "cache_ttl": "300s",
  "name": "Custom Error",
  "endpoints": [
    {
      "endpoint": "/error",
      "method": "GET",
      "extra_config": {
        "github.com/devopsfaith/krakend-lua/router": {
          "pre": "--custom_error('from endpoint router pre', 404)"
        },
        "github.com/devopsfaith/krakend-lua/proxy": {
          "pre": "--custom_error('endpoint proxy pre', 404)",
          "post": "custom_error('endpoint proxy post', 404)"
        }
      },
      "backend": [
        {
          "host": "http://localhost:8080",
          "method": "GET",
          "url_pattern": "/404",
          "extra_config": {
            "github.com/devopsfaith/krakend-lua/proxy/backend": {
              "pre": "--custom_error('backend proxy pre', 404)",
              "post": "custom_error('backend proxy post', 404)"
            },
            "github.com/devopsfaith/krakend/http": {
              "return_error_details": "api"
            }
          }
        }
      ]
    }
  ]
}
```
```
krakend run -c custom_error.json
```

Expectation is that the custom_error helper will send the response code for post scripts as well.

**Comment by mathewsheets** [comment]
Any chance I can get some direction in the near future. Thanks.

**Comment by taofather** [comment]
Same issue here. It would be great to provide some examples in the docs of status code manipulations, using lua or Go plugins.

**Comment by taofather** [comment]
Hi @mathewsheets, as mentioned in the docs, "post" scripts are only allowed in the backend extra_config.

However, a little bit more examples concerning response body treatment in proxy ("pre") scripts would be appreciated.

**Comment by mathewsheets** [comment]
Hello, yes, you are correct, the "pre" script in the backend is not valid. With regards to the "post" scripts and leveraging the custom_error function, I can verify in the logging that the function is called: "Error #01: backend proxy post", but my expectation would be for the endpoint / proxy / post script to send a response code of 404 to the caller.

For my use case, I would like to evaluate the JSON response of:

{
    "error_api": {
        "http_status_code": 404,
        "http_body": "404 page not found"
    }
}

and would like to return a response status of 404 and response text of "Not Found"

**Comment by tiberiu89** [comment]
Anything on this? I have the same issue, I would expect to be able to run a post script in the backend or endpoint and be able to throw a custom error, thus changing the default 500 output in case some backend is returning > 400
