### ISSUE TITLE
krakend cannot cannot validate certificate for my backend server : "x509: cannot validate certificate"

### ISSUE THREAD

**Issue by akarsh1997** [krakendio/krakend-ce#321]
On running **krakend run -c krakend.json --port 8080 -d**. for the below endpoint configuration provided is returning me this error :

**,[GIN] 2021/06/18 - 15:27:23 | 500 |   46.375329ms |             ::1 | POST     "/auth/session"
_Error #01: Post "https://10.164.75.5:8443/auth/session": x509: cannot validate certificate for 10.164.75.5 because it doesn't contain any IP SANs_
Where 10.164.75.5 is my backend server configured with self signed cert.**

I am using curl command - _curl -I --location --insecure --request POST 'http://localhost:8080/auth/session' --header 'Authorization:  xxxxxxxxxxxxx' --header 'Content-Type: xxxxxxxxxxx'_   to send the request.

```
{
      "endpoint": "/auth/session",
      "method": "POST",
      "output_encoding": "no-op"

      "extra_config": {
            "tls": {
            "disabled": true
        }
      },
      "headers_to_pass": [
        "Authorization",
        "Content-Type"
      ],
      "backend": [
        {
          "url_pattern": "/auth/session",
          "encoding": "no-op",
          "sd": "static",
          "method": "POST",
          "extra_config": {
                "tls": {
                    "disabled": true
                }
            },
          "host": [
            "https://10.164.75.5:8443"
          ],
          "disable_host_sanitize": true
        }
      ],
      "extra_config": {
            "tls": {
                "disabled": true
            }
        }
    },
```
Any idea why is this happening ?
Also for this endpoint forwarding simply to nginx website runs fine in my case. Below is the endpoint config 

```
{
      "endpoint": "/nginxorg",
      "method": "GET",
      "output_encoding": "no-op",
      "backend": [
        {
          "encoding": "no-op",
          "sd": "static",
          "method": "GET",
          "host": [
            "https://www.nginx.org"
          ],
          "disable_host_sanitize": true
        }
      ]
    }
```

**Comment by kpacha** [comment]
it looks like your backends are using a certificate signed by an authority unknown by your gateway. Add your CA to your gateway OS and everything will run properly.

One final note: when using the `-k/--insecure` flag, curl  doesn't validate the certificate published by the server. If you repeat the test without the flag you'll see a similar error

**Comment by akarsh1997** [comment]
Hi tysm for the response,
I followed your suggestion and added the CA certificate to my OS trust store : 
Please find the steps below
1.**openssl genrsa -des3 -out CA-key.pem 2048
2. openssl req -new -key CA-key.pem -x509 -days 1000 -out rootca.pem**
3. Copied the rootca.pem to **/etc/pki/ca-trust/source/anchors/** in my Gateway OS
4. update-ca-trust
5. Started my backend webserver 10.164.75.5 again 
6. ran **krakend run -c krakend.json --port 8080 -d**.
7. **curl -I --location --request POST 'http://127.0.0.1:8080/auth/session' --header 'Authorization: xxxxxxxxxxxxxxx' --header 'Content-Type: xxxxxxxxxxxxxxxx'**

```
2021/06/20 08:24:55  DEBUG: [lua: no extra config]
2021/06/20 08:24:55  INFO: [JOSE: validator disabled for the endpoint /nginxorg]
2021/06/20 08:24:55  DEBUG: [botdetector:  no config defined for the module]
[GIN-debug] GET    /nginxorg                 --> github.com/luraproject/lura/router/gin.CustomErrorEndpointHandler.func1 (3 handlers)
2021/06/20 08:24:55  DEBUG: [http-server-handler: no extra config]
2021/06/20 08:25:00  INFO: [registering usage stats for cluster ID 'x9+G35KqNyQXLqlPLEBsjJT1NeIIPzc9GDn/NizGvkg=']
[GIN] 2021/06/20 - 08:25:03 | 500 |    1.626948ms |       127.0.0.1 | POST     "/auth/session"
Error #01: Post "https://10.164.75.5:8443/auth/session": remote error: tls: handshake failure
[GIN] 2021/06/20 - 08:31:06 | 500 |     1.25325ms |       127.0.0.1 | POST     "/auth/session"
Error #01: Post "https://10.164.75.5:8443/auth/session": remote error: tls: handshake failure

```


Now I am facing this error . Please help.

**Comment by c-nv-s** [comment]
I feel there should be a setting here to allow performing insecure requests (like the curl --insecure flag) to the backend... at least a dev-mode type flag.
I'm experiencing the same issue and it seems like a lot of hoops to jump through especially when you are running krakend via docker container.

**Comment by alombarte** [comment]
The flag `allow_insecure_connections` has been added to KrakenD 2.1 (soon to be relased). You will be able to add it in your configuration or start the service with `KRAKEND_ALLOW_INSECURE_CONNECTIONS=true krakend run -c krakend.json`
