### ISSUE TITLE
Middleware Stacking/Sequencing After Lua

### ISSUE THREAD

**Issue by is911** [krakendio/krakend-ce#342]
Hi, I have a lua script middleware thats working; which I would like to further refine and manipulate with flatmaps, mapping, etc. But these middleware doesnt seem to have any effect when Lua is used. Any ideas how to sequentially apply these middlewares one after another?

**Comment by alombarte** [comment]
Hi @is911 , you can combine Lua with other manipulation options. You have to be aware of the position and type of Lua you are using and when it intervenes in the fetching/requesting/merging process

![Lua](https://www.krakend.io/images/documentation/diagrams/lua-2.mmd.png)
