### ISSUE TITLE
How about using LoadWithLogger in LoadPlugins method

### ISSUE THREAD

**Issue by banv** [krakendio/krakend-ce#343]
I was created a custom plugin but althrough defined RegisterLogger, it not be called. 
I see plugin.go, it call client.Load and server.Load without specific logger.
How about using client.LoadWithLogger and server.LoadWithLogger ? 

I made a pull request https://github.com/devopsfaith/krakend-ce/pull/344

**Comment by kpacha** [comment]
fixed at https://github.com/krakendio/krakend-ce/pull/374
