### ISSUE TITLE
Krakend Custom JWT Validation

### ISSUE THREAD

**Issue by gokhandroid** [krakendio/krakend-ce#351]
Hello,

I have a problem with me. I work with Microservis architecture. There is an Auth.API in the architecture and I produce JWT with this service and I can do the validation process here. I need to verify with this service before all other services are called. Because I have different criteria for the verification process. This is why I need to make a "isTokenValid" request before Krakend to Auth.api service. However I couldn't find that how to do that. Can you help me?

**Comment by kpacha** [comment]
check my comment on this other issue: https://github.com/krakendio/krakend-ce/issues/449#issuecomment-1157987612

cheers!
