### ISSUE TITLE
JWT Validation is ignored when token is not provided

### ISSUE THREAD

**Issue by droslean** [krakendio/krakend-ce#399]
I am following this documentation: https://www.krakend.io/docs/authorization/keycloak

In the `Protecting endpoints with Keycloak tokens` part:
```json
    "extra_config": {
        "github.com/devopsfaith/krakend-jose/validator": {
            "alg": "RS256",
            "jwk-url": "http://KEYCLOAK:8080/auth/realms/master/protocol/openid-connect/certs",
            "disable_jwk_security": true
        }
    },
```

The problem is that when we access the endpoint, that is supposed to be protected by keycloak, without any token in the headers, the request is being redirected in the backend.

I would expect krakend to deny the call if there is no token provided. Is this a bug or more configuration is needed? If so, why the documentation doesn't explain it well?

**Comment by rafaumlemos** [comment]
Hi, i'm using keycloak validation with krakend and works well, krakend returns 401 when the authorization token is not provided.
Try with my configuration:
`
{
  "version": 2,
  "extra_config": {},
  "timeout": "5000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "service-name",
  "endpoints": [
    {
      "endpoint": "/myendpoint",
      "headers_to_pass": ["Authorization"],
      "querystring_params": [
        "*"
      ],
      "method": "GET",
      "output_encoding": "no-op",
      "extra_config": {
        "github.com/devopsfaith/krakend-jose/validator": {
          "alg": "RS256",
          "jwk-url": "https://keycloak-service.dev/auth/certs"
        }
      },
      "backend": [
        {
          "url_pattern": "/foo",
          "encoding": "no-op",
          "method": "GET",
          "extra_config": {},
          "host": [
            "https://my-api.dev"
          ],
          "disable_host_sanitize": false
        }
      ]
    }
  ]
}
`

**Comment by rafaumlemos** [comment]
Hi, i'm using keycloak validation with krakend and works well, krakend returns 401 when the authorization token is not provided.
Try with my configuration:
```json
{
  "version": 2,
  "extra_config": {},
  "timeout": "5000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "service-name",
  "endpoints": [
    {
      "endpoint": "/myendpoint",
      "headers_to_pass": ["Authorization"],
      "querystring_params": [
        "*"
      ],
      "method": "GET",
      "output_encoding": "no-op",
      "extra_config": {
        "github.com/devopsfaith/krakend-jose/validator": {
          "alg": "RS256",
          "jwk-url": "https://keycloak-service.dev/auth/certs"
        }
      },
      "backend": [
        {
          "url_pattern": "/foo",
          "encoding": "no-op",
          "method": "GET",
          "extra_config": {},
          "host": [
            "https://my-api.dev"
          ],
          "disable_host_sanitize": false
        }
      ]
    }
  ]
}
```

**Comment by droslean** [comment]
@alombarte Krakend doesn't generate any logs related to this issue.

**Comment by ethanpooley** [comment]
@droslean To get KrakenD to generate logs related to your issue, try the [`operation_debug`](https://www.krakend.io/docs/authorization/jwt-validation/) setting:
> operation_debug (bool): When true, any JWT validation operation gets printed in the log with a level ERROR. You will see if a client does not have sufficient roles, the allowed claims, scopes, and other useful information.

So:
```
"extra_config": {
    "auth/validator": {
        "operation_debug": true,
        ...
    }
}
```

**Comment by droslean** [comment]
@ethanpooley No logs are being generated. @kpacha is there any fix for this? 

@rafaumlemos Your configuration doesn't work either. I can still access the endpoint without any token.

**Comment by droslean** [comment]
```json
{
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "name": "Krakend",
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "port": 8080,
  "disable_rest": false,
  "endpoints": [
    {
      "endpoint": "/menus/{domain}",
      "method": "GET",
      "output_encoding": "json",
      "backend": [
        {
          "url_pattern": "/menus/{domain}",
          "encoding": "json",
          "method": "GET",
          "extra_config": {
            "qos/http-cache": {
              "shared": true
            },
            "auth/validator": {
              "alg": "RS256",
              "operation_debug": true,
              "jwk_url": "http://keycloak.keycloak:8443/auth/realms/master/protocol/openid-connect/certs",
              "disable_jwk_security": true,
              "cache": true
            }
          },
          "host": [
            "http://mybackend:8080"
          ]
        }
      ],
      "concurrent_calls": 3
    }
  ]
}
```

Using the above configuration the krakend instance generates those logs on startup
```
2022/09/01 14:43:40 KRAKEND DEBUG: [ENDPOINT: /menus/:domain] Building the proxy pipe
2022/09/01 14:43:40 KRAKEND DEBUG: [BACKEND: /menus/{{.Domain}}] Building the backend pipe
2022/09/01 14:43:40 KRAKEND DEBUG: [ENDPOINT: /menus/:domain] Building the http handler
2022/09/01 14:43:40 KRAKEND DEBUG: [ENDPOINT: /menus/:domain][JWTSigner] Signer disabled
2022/09/01 14:43:40 KRAKEND INFO: [ENDPOINT: /menus/:domain][JWTValidator] Validator disabled for this endpoint
2022/09/01 14:43:40 KRAKEND INFO: [SERVICE: Gin] Listening on port: 8080
```

@kpacha So the https://www.krakend.io/docs/authorization/keycloak/ documentation is wrong. Please help.

**Comment by kpacha** [comment]
no, it is not. notice you placed the extra config at the backend level instead of at the endpoint.

you can see other working examples at the playground: https://github.com/krakendio/krakend-playground/blob/master/krakend/krakend.json#L168-L184

**Comment by droslean** [comment]
@kpacha Thanks! Is there any way to apply this configuration for all endpoints once in the config or I have to specify it in every one?
