### ISSUE TITLE
Custom tags in traces

### ISSUE THREAD

**Issue by rubytech-avsorokin** [krakendio/krakend-ce#416]
**Is your feature request related to a problem? Please describe.**

I need to provide trace as well as logs with some custom tags. It needs to correlate traces with logs.
It's already done in datadog exporters. Is it possible to scale this possibility up to all traces?

**Describe the solution you'd like**
Add tags at github_com/devopsfaith/krakend-opencensus global level and export It to Zipkin/Jaeger etc

**Comment by alombarte** [comment]
Thanks @rubytech-avsorokin ,

I don't think tags can be added at the global level, as each exporter has its own settings, and not all support tags. Nevertheless, I leave this issue open for investigation as some mayeb could (e.g: https://pkg.go.dev/contrib.go.opencensus.io/exporter/jaeger).

Opencensus will be deprecated at some point by OpenTelemetry when it supports both metrics and traces.
