### ISSUE TITLE
How to get TraceID / SpanID in GIN logger 

### ISSUE THREAD

**Issue by rubytech-avsorokin** [krakendio/krakend-ce#424]
**Describe what are you trying to do**
I heed to configure KrakenD GIN logger to log trace ids and/or span ids to make it possible to correlate traces with logs 

**Your configuration file**
The content of your `krakend.json`. When using the flexible configuration option, the computed file can be generated using `FC_OUT=out.json`
```
{
  "version": 2,
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level": "DEBUG",
      "prefix": "[KRAKEND]",
      "syslog": false,
      "stdout": true,
      "format": "default"
    },
    "github.com/devopsfaith/krakend/http": {
      "return_error_details": "backend_alias"
    },
    "github_com/devopsfaith/krakend-opencensus": {
      "sample_rate": 100,
      "reporting_period": 1,
      "enabled_layers": {
        "backend": true,
        "router": true,
        "pipe": true
      },
      "exporters": {
        "prometheus": {
          "port": 9091,
          "namespace": "krakend"

        },
        "zipkin": {
            "collector_url": "{{ .tracing.CollectorUrl }}",
            "service_name": "{{ .tracing.ServiceName }}"
        }
      },
      "logger": {
          "stats": true,
          "spans": true
      }
    }
  },...
```

**Logs**
If applicable, any logs you saw in the console and debugging information

[GIN] 2022/02/21 - 16:43:10 | 200 |  262.300364ms |      10.254.0.8 | GET      "/apis/ts/0.1/tasks"

How to get TraceIDs right here?
Is there any config options or it heeds to middleware/plugin development?

**Comment by darren-bell-optiva** [comment]
@rubytech-avsorokin Did you make any progress on this? I essentially want to do the same thing. I'm not sure I'm missing something but I don't see the trace/span ids logged as the configuration suggests

**Comment by taik0** [comment]
For this, you need to build your own version injecting a log formatter to gin using this[ lura option](https://github.com/luraproject/lura/blob/b3ca60fa826b67ddd1f9b43020021006dd32f401/router/gin/engine.go#L26)
This is the only way to modify what gin is going to write in the logs.
https://github.com/gin-gonic/gin/blob/master/logger.go#L52-L79

**Comment by cmorent** [comment]
@taik0 but then, what is this part of the config suppose to do?

```
"logger": {
  "stats": true,
  "spans": true
}
```
