### ISSUE TITLE
Request to GCP Appengine protected with IAP

### ISSUE THREAD

**Issue by ahmadissa** [krakendio/krakend-ce#435]
**Describe what are you trying to do**
Hi, I am trying to request backend API hosted on GCP AppEngine and protected by GCP Identity Aware Proxy, which can be done as described in the below link:
https://cloud.google.com/run/docs/authenticating/service-to-service#run-service-to-service-example-go

My question: is there a plugin I can use to do that? 

if not,  I am thinking of generating the token outside Krakend and saving it in ENV variables, Can I pass the token from ENV variable to backend headers as Authorization: Bearer ID_TOKEN

I know that I can pass Authorization Bearer header as below, but can this set from ENV variable at run time, as I need to refresh the token every 1hr

```
 "modifier/martian": {
        "header.Modifier": {
          "scope": ["request"],
          "name": "Authorization",
          "value": "Bearer '$GCP_TOKEN'"
        }
      }
 ```

**Commands used**
How did you start the software?
```
#Example:
krakend run -d -c krakend.json


**Logs**
If applicable, any logs you saw in the console and debugging information

**Comment by alombarte** [comment]
Hello @ahmadissa ,

You can pass a value in the environment variables and set it with [flexible configuration syntax](https://www.krakend.io/docs/configuration/flexible-config/). For instance, you could do:

```
 "modifier/martian": {
        "header.Modifier": {
          "scope": ["request"],
          "name": "Authorization",
          "value": "Bearer '{{ env "GCP_TOKEN" }}'"
        }
      }
```

**Comment by ahmadissa** [comment]
Hi @alombarte,

thanks for the reply. The GCP token is valid for 1 hr, do I need to reload krakend to be able to read the new token from the env variable every 1 hr?

**Comment by alombarte** [comment]
If you want to use this "hack" with martian, then yes, you should apply the configuration every hour.

But the usual way of approaching this problem would be to use for instance client credentials and let the gateway negotiate the token for you. [Client credentials is documented here](https://www.krakend.io/docs/authorization/client-credentials/)
