### ISSUE TITLE
Should endpoint timeout always be in ms?

### ISSUE THREAD

**Issue by amokkara** [krakendio/krakend-ce#436]
I have endpoint timeout set as 
`"timeout": "120s",`

but krakend.json has time out as 

`{
    "version": 2,
    "timeout": "30000ms",`
    
the endpoint timeout never seems to be applied in requests. if request take more than 30 sec, its returning 500 internal server error. There is no error thrown from backend. Error is from krakend itself.

Why is the endpoint timeout not coming into effect? should it be in "ms" rather than "s"?
I couldnt find this information in any documentation.

**Comment by alex-pobeditel-2004** [comment]
Nobody has answered it but issue still persists on version 2.0.4.  

Endpoint-specific timeout **makes no effect** at all, does not matter `ms` or `s` are used. But there is exactly that [example in official docs](https://www.krakend.io/docs/throttling/timeouts/).  

Also, I have `"version": 3` in config

**Comment by kpacha** [comment]
I can't reproduce. Here you have the results of a quick test:

Backend:
```
package main

import (
	"log"
	"net/http"
	"strings"
	"time"
)

func main() {
	http.ListenAndServe(":8081", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		parts := strings.Split(r.URL.Path, "/")
		timeout, err := time.ParseDuration(parts[2])
		if err != nil {
			log.Println(err.Error())
		}
		time.Sleep(timeout)
		w.Write([]byte(`{"a":[1,2,3], "b":[9,7,5,3,1]}`))
	}))
}
```

KrakenD config:
```
{
    "version":3,
    "timeout": "300s",
    "endpoints":[
    	{
    		"endpoint":"/{timeout}",
    		"backend":[
    			{
    				"url_pattern":"/slow/{timeout}",
    				"host":["http://127.0.0.1:8081"]
    			}
    		]
    	}
    ]
}
```

KrakenD logs:
```
[GIN] 2022/06/03 - 21:35:52 | 200 |  1.000453678s |       127.0.0.1 | GET      "/1s"
[GIN] 2022/06/03 - 21:36:10 | 200 | 10.009075939s |       127.0.0.1 | GET      "/10s"
[GIN] 2022/06/03 - 21:37:09 | 200 | 50.049166777s |       127.0.0.1 | GET      "/50s"
[GIN] 2022/06/03 - 21:41:22 | 200 |         3m20s |       127.0.0.1 | GET      "/200s"
2022/06/03 21:46:36 KRAKEND ERROR: [ENDPOINT: /:timeout] context deadline exceeded
[GIN] 2022/06/03 - 21:46:36 | 500 |          5m0s |       127.0.0.1 | GET      "/320s"
``` 

as the log shows, the backend actually blocks the response as long as requested and the gateway honors the defined timeout (and it can be defined using duration units other than `ms`)

**Comment by alex-pobeditel-2004** [comment]
@kpacha hello!

Your test checks different thing - I (and hopefully @amokkara) was talking about this type of config (globally set timeout is **overridden** in endpoint):

```
{
    "version":3,
    "timeout": "10s",
    "endpoints":[
    	{
    		"endpoint":"/{timeout}",
    		"backend":[
    			{
    				"url_pattern":"/slow/{timeout}",
    				"host":["http://127.0.0.1:8081"],
                                "timeout": "30s",
    			}
    		]
    	}
    ]
}
```
So in this case request `GET      "/15s"` will fail but it must succeed due to the documentation (["Endpoint-specific timeout" chapter](https://www.krakend.io/docs/throttling/timeouts/)).

**Comment by alex-pobeditel-2004** [comment]
@kpacha sorry for late response - you are absolutely correct! 🙏

My huge mistake was using Flexible Configuration and thinking that just specifying endpoint timeout will be enough for it to work - I just forgot to pass endpoint timeout in endpoint template - I fixed it and everything works as expected now 🫣

Thank you again for such a detailed introspection of the "problem"!
