### ISSUE TITLE
Plugin build failing with 2.0

### ISSUE THREAD

**Issue by henrisokka** [krakendio/krakend-ce#439]
When trying to build plugins for 2.0 with it's dependencies we got following error:

```
# github.com/klauspost/compress/zstd/internal/xxhash
asm: xxhash_amd64.s:120: when dynamic linking, R15 is clobbered by a global variable access and is used here: 00092 (/go/pkg/mod/github.com/klauspost/compress@v1.13.1/zstd/internal/xxhash/xxhash_amd64.s:120)       ADDQ    R15, AX
asm: assembly failed
```

The dependency `klauspost/compress` has already patched the bug (https://github.com/klauspost/compress/pull/430) but you're InfluxDB-library seems to be still using old version through it's `github.com/influxdata/influxdb` -dependency

We were able to workaround the issue by just editing go.mod to `github.com/klauspost/compress v1.13.6` and  build a new Docker image.

Steps to reproduce:

1. clone krakend-ce and go to folder
2. `git checkout tags/v2.0.0` 
3. copy your plugin code to `krakend-ce/plugins`
4. `go build -buildmode=plugin plugins/plugin.go`

**Comment by flyznex** [comment]
Check my Issue #437 and you need update xxhash to version v2.1.2 to solve it

**Comment by taik0** [comment]
Hi @henrisokka can you share some plugin example to trigger this error? With my current plugins I cannot reproduce it.
