### ISSUE TITLE
Unable to build: missing github.com/auth0-community/go-auth0@v1.0.0

### ISSUE THREAD

**Issue by slaveofcode** [krakendio/krakend-ce#446]
**Describe what are you trying to do**
Hi, I'm trying to build krakend on local after clone the repo, the results are the same for both branch `master` and `v2.0.0` tag.
Please advice 

**Commands used**
```
make build
```

**Logs**
```
Building the binary...
go: github.com/auth0-community/go-auth0@v1.0.0: reading github.com/auth0-community/go-auth0/go.mod at revision v1.0.0: git ls-remote -q origin in /home/kresna/.gvm/pkgsets/go1.18/global/pkg/mod/cache/vcs/bee1d153ff1c2bd8b6dac85d540845eaa2b6698f511989f8676c79eb0a0beaad: exit status 128:
        ERROR: Repository not found.
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
make: *** [Makefile:87: build] Error 1
```
![Screenshot from 2022-03-26 20-03-19](https://user-images.githubusercontent.com/13603341/160240776-37e7afda-fe2c-4e9c-be16-099e38fff068.png)

**Comment by alombarte** [comment]
Auth0 deleted this library and this is the reason why this error happened. Newer KrakenD versions corrected this.
