### ISSUE TITLE
Async request modifiers

### ISSUE THREAD

**Issue by yanivshiloah** [krakendio/krakend-ce#449]
Hey, 

Can request modifiers be async?
I use auth0 and I want to allow admin users to make requests on behalf of another user so I thought of the following:
1. UI sends the "user-id-override" header to Krakend
2. Krakend validates bearer token and if is valid passes roles in an header.
3. **(This is the request modifier part I want to implement as plugin):** 
If role = admin and "user-override-id" header exists, I want to make a request to an inner auth service to get details about this user (there's certain user_metadata I need) and put it on the headers.

Is it possible?
Is there another way to implement this behavior?

Thanks

**Comment by kpacha** [comment]
you can inject that logic using a custom request modifier plugin (https://www.krakend.io/docs/extending/plugin-modifiers/) but you should be aware of the implications of that kind of token introspection (performance, resource consumption, possible SPoF, etc)
