### ISSUE TITLE
Put X-Correlation-Id in request header

### ISSUE THREAD

**Issue by hookenful** [krakendio/krakend-ce#457]
Hello there!

 I am finding solution to generate X-Correlation-Id on krakend gateway own. Is it possible?

Or I supposed to use some tracing solutions built in KrakenD, where that header apply by default? 
Thanks for any help!

**Comment by kpacha** [comment]
You can either create a lua snippet or a request modifier plugin to generate it.

Regarding the tracing solution, krakend supports opencensus and uses B3 as tracing context standard
