### ISSUE TITLE
Error installing krakand-integration

### ISSUE THREAD

**Issue by trojanh** [krakendio/krakend-ce#470]
**Describe the bug**
When installing krakend-integration using below command

`go install github.com/devopsfaith/krakend-ce/v2/cmd/krakend-integration@v2.0.1   `        

I get following error
                                                                          
```
go install: github.com/devopsfaith/krakend-ce/cmd/krakend-integration@v2.0.1: github.com/devopsfaith/krakend-ce@v2.0.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

because of which the package does not install. 

I also verified the install location path 
`/.gvm/pkgsets/go1.17/global/bin`

it has no entry for `krakend-integration`

Edit:

Workaround for this is 
1. `git clone https://github.com/devopsfaith/krakend-ce`
2. `cd krakend-ce/cmd/krakend-integration`
3.  `go install` this will install the go package locally and you should find it in `ls $GOPATH/bin`
4. `krakend-integration` command should be available to test now.

**Comment by trojanh** [comment]
updated the command in docs as per @kpacha suggestions
https://github.com/devopsfaith/krakend-documentation/pull/153/files

**Comment by allanalarcon** [comment]
I have the same error, in docs the command is:
`go install github.com/krakendio/krakend-ce/cmd/krakend-integration@v2.0.5`

I get following error
`go: github.com/krakendio/krakend-ce/cmd/krakend-integration@v2.0.5: github.com/krakendio/krakend-ce/cmd/krakend-integration@v2.0.5: invalid version: unknown revision cmd/krakend-integration/v2.0.5`

If I used the command:
`go install github.com/krakendio/krakend-ce/v2/cmd/krakend-integration@v2.0.5`

I get following error
```
go: github.com/krakendio/krakend-ce/v2/cmd/krakend-integration@v2.0.5 (in github.com/krakendio/krakend-ce/v2@v2.0.5):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```
