### ISSUE TITLE
Dynamicly setting the host (with lua or something else)

### ISSUE THREAD

**Issue by RubyKozel** [krakendio/krakend-ce#502]
Hi,
I'm using karakend version 2.0.3 and i'm trying to do a simple request to a DYNAMIC host.
From what I've seen in the documentation, you cannot set the host dynamically, but you can manipulate the request before it reaches the backend with Lua.
So what I did is to create a HTTP server handler that sets a dynamic host under the header `x-dynamic-host`
I then try to read it via the lua script in the 'modifier/lua-backend' backend plugin - but this header is not being passed to the request, although I'm passing all the headers `input_headers: *`

I'm trying to understand if this is even possible and if I'm doing something wrong.
An example of the configuration file:

```json
{
    "version": 3,
    "port": 8080,
    "host": [ "foo.bar.com"]
   "plugin": {
      "pattern": ".so",
      "folder": "./"
    },
    "extra_config": {
      "router": {
        "disable_health": true
      },
      "github_com/devopsfaith/krakend/transport/http/server/handler": {
        "name": [
          "dynamic-host-plugin"
        ],
      }
    },
   "endpoints": [
{
      "endpoint": "/foo",
      "method": "GET",
      "input_headers": [
        "*"
      ],
      "input_query_strings": [
        "*"
      ],
      "output_encoding": "no-op",
      "timeout": "120s",
      "backend": [
        {
          "url_pattern": "/",
          "encoding": "no-op",
          "input_headers": [
            "*"
          ],
          "input_query_strings": [
            "*"
          ],
          "timeout": "120s",
          "host": [
            "https://foo.bar.com"
          ],
          "extra_config": {
            "modifier/lua-backend": {
              "allow_open_libs": true,
              "pre": "local req = request.load(); req:url(req:headers('x-dynamic-host') .. req:path() .. req:query()); print('AFTER PROXY, host='); print(req:url())"
            }
          }
        }
      ]
    }
   
   ]
}
```

all the plugin does is setting the header: `r.Header.Set("x-dynamic-host", dynamicHost) // dynamicHost is for e.g "foo.baz.com"`

**Comment by taik0** [comment]
Hi @RubyKozel 

I think that with LUA you need to canonicalize the header name:
```
req:headers('X-Dynamic-Host')
```

**Comment by RubyKozel** [comment]
@taik0 thanks for the quick response - that did the trick! much appreciated.

Follow-up question - is there a best practice for setting the host dynamically? This solution looks a bit more of a hack than a real solution...
