### ISSUE TITLE
Flexible Configuration - editing advice

### ISSUE THREAD

**Issue by nikobonomi** [krakendio/krakend-ce#503]
Hello there,

Just started using KrakenD and it's amasing, quite easy to setup and run.

Now, I'm preparing a configuration for a gateway that will potentially have some hundreds of endpoints. My configuration uses Keycloak for some, requests (probably for all, but it's not already defined at this stage). So, I need to place the same auth/validator (except for the roles) in all the endpoints, something like this:
```json
[...]
      "extra_config": {
        "auth/validator": {
          "alg": "RS256",
          "disable_jwk_security": true,
          "jwk_url": "http://keycloak:8080/realms/myRealm/protocol/openid-connect/certs",
          "roles_key_is_nested": true,
          "roles_key": "realm_access.roles",
          "roles": [
            "admin"
          ]
        }
      },
[...]
```

This results in a lot of boilerplate code and also if (for example) the keycloak host ever change, I need to manually make a change in each endpoint. -> not very ideal!   
So i discovered the amazing world of the flexible configuration, I followed [this tutorial](https://www.krakend.io/docs/configuration/flexible-config/) on the krakend website, thus creating a krakend.tmpl and an auth.tmpl. Resulting in somethings like this:   
*krakend.tmpl*
```json
[...]
      "extra_config": {
        "auth/validator": {
          {{template "auth.tmpl" .keycloak }},
          "roles": ["org-admin"]
        }
      },
[...]
```
and the *auth.tmpl* (which get a keycloak.json setting file containing all the parameters):
```json
[...]
  "alg": "{{ .alg }}",
  "disable_jwk_security": true,
  "jwk_url": "{{ .jwk_url }}",
  "roles_key_is_nested": {{ .roles_key_is_nested }},
  "roles_key": "{{ .roles_key }}",
[...]
```

So here everythong is actually working! yay!... But then I noticed that I did not get any support from my IDE... no folding, no color, no formatting... no schema check... nothing...   
Thus thinking of maintaining a configuration file with 100+ endpoints, it becomes a task quite messy, prone to errors and generally it is easier to waste time.   

That being said, I'm here seeking advice on how you guys manage this """issue""", do you simply deal with it? or there is a smart trick of some sort? As IDE of choice we use Intellij Idea, but I'm open to other solutions as well :)   

EDIT: I saw that Visual Studio code allows the folding :)

**Comment by alombarte** [comment]
Hi @nikobonomi, there are several ways to get over this "issue", here there are a few ideas:

1) You can make your IDE of choice to do a `krakend check` in the background after every save, and save the result of the `FC_OUT` in a local file (e.g: krakend.json). Check this file in a new tab.
2) You can use [KrakenD hot reload Docker image](https://www.krakend.io/docs/developer/hot-reload/) and the image will generate the final krakend.json after every save by itself. You can have the final krakend.json file opened in a tab in your editor and check how it is doing after each reload.
3) You can use partial validation on external JSON templates if you want to validate a small object. E.g. notice the `$schema`:
```
{
    "$schema": "https://www.krakend.io/schema/auth/validator.json",
    "alg": "RS256",
    "disable_jwk_security": true,
    "jwk_url": "http://keycloak:8080/realms/myRealm/protocol/openid-connect/certs",
    "roles_key_is_nested": true,
    "roles_key": "realm_access.roles",
    "roles": [
      "admin"
    ]
}
```

**Comment by nikobonomi** [comment]
Hello there @alombarte, thanks you for giving some options. Sure I will try them soon!

Thanks!
