### ISSUE TITLE
Grafana dashboard with one entry per endpoint variable

### ISSUE THREAD

**Issue by Dorkside** [krakendio/krakend-ce#506]
**Environment info:**

* KrakenD version: 2.0.4
* System info: Linux 4.18.0-305.40.2.el8_4.x86_64 x86_64
* Hardware specs: N/A
* Backend technology: Node
* Additional environment information:

**Describe what are you trying to do**:
I am trying to obtain an API dashboard in Grafana with detailed information on response times on an endpoint configured as follows:
```
    {
      "endpoint": "/api/v4/tenants/{tenant}/computation",
      "method": "POST",
      "output_encoding": "no-op",
      "input_query_strings": ["*"],
      "input_headers": ["*"],

      "backend": [
        {
          "encoding": "no-op",
          "url_pattern": "/api/v4/tenants/{tenant}/computation",
          "host": [
            "***********************************"
          ]
        }
      ]
    },
```
This configuration is pretty good for obtaining a deshboard using the native influxdb exporter, but only generates a single entry for the endpoint in the following format :
`/api/v4/tenants/:tenant/computation`

I am wondering if there is any way to export/display the data differently as to have one entry per tenant:
`/api/v4/tenants/tenant1/computation`
`/api/v4/tenants/tenant2/computation`
...

**Your configuration file**:

```json
{
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "extra_config": {{ marshal .service.extra_config }},
  "timeout": "15000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "api.gateway",
  "endpoints": [
            {{ range $idx, $endpoint := .external.endpoints }}
            {{if $idx}},{{end}}
            {{marshal $endpoint}}
            {{ end }},
            {{ range $idx, $endpoint := .computation_v4.endpoints }}
            {{if $idx}},{{end}}
            {{marshal $endpoint}}
            {{ end }}
        ]
}
```

**Comment by kpacha** [comment]
The metrics collector uses the pattern instead of using the actual path in order to keep the cardinality of the tag under control. If you want to graph the actual path, you'll need to process your access log (E.g: with ELK)
