### ISSUE TITLE
Question: Store Tokens in Secure HTTP Only Cookies?

### ISSUE THREAD

**Issue by a-n-d-i** [krakendio/krakend-ce#515]
Hi,

the current ietf draft for browser based apps (see below, 6.1) states that, atm, there is no way to store credentials securely in the browser in a way which allows Javascript to access them. Henceforth Bearer Token Auth is out for SPAs, secure httponly cookies are the only option.

We're doing stateless sessions with the tokens encrypted in a cookie which are decrypted in our API Gateway which uses OIDC Authorization Code Flow to log in the user. Now, we're thinking of switching to krakend ce and are wondering if this is possible / how we could achieve that. I would be very thankful for any Pointers.

https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps#page-6

Thanks, Andi

**Comment by kpacha** [comment]
KrakenD allows you to pass a JWT inside a cookie. Check the option `cookie_key` from this documentation entry: https://www.krakend.io/docs/authorization/jwt-validation/#jwt-validation-settings

The JWT should not be encrypted, just signed by the issuer

Cheers!
