### ISSUE TITLE
Access to logs while running krakend-integration

### ISSUE THREAD

**Issue by qshanahan-springhealth** [krakendio/krakend-ce#526]
**Version of KrakenD you are using**
2.0.5 CE

**Is your feature request related to a problem? Please describe.**
I am getting a 500 status/nil response on my specw, even though I've tried everything I can think of to replicate the error with krakend, but it works (in the browser, curl, etc)

**Describe the solution you'd like**
logs in stdout or a file

**Describe alternatives you've considered**
I tried using syslog, but nothing seems to get logged to OS X's default syslog file. this is using regular krakend or krakend-integration

**Comment by MKITConsulting** [comment]
I face the same issue and is a real pain to me as you cannot see why your test specs fail. 

**_Please add a command line property or environment varialbe to `krakend-integration` to enable a debug log mode._**

**Comment by qshanahan-springhealth** [comment]
this could be solved with a log file option for the telemetry plugin. if this seems like a worthwhile addition I can try to implement it

**Comment by qshanahan-springhealth** [comment]
@kpacha looking at https://github.com/krakendio/krakend-gologging/blob/master/log.go this seems like it would be trivial to do. Mind if I open a PR? e.g:

```json
    "telemetry/logging": {
      "level": "DEBUG",
      "prefix": "[KRAKEND]",
      "syslog": true,
      "stdout": true,
      "file": "path/to/file.log"
    }
```

**Comment by qshanahan-springhealth** [comment]
following up on this. I would like to make this contribution assuming maintainers think its valuable.

**Comment by kpacha** [comment]
@qshanahan-springhealth thanks for the investment and the willing to contribute to the project! 

Yes, we think being able to write logs to the filesystem is valuable. We have invested some time improving our syslog exporter on our latest release (v2.1.0).

We think sending the logs to syslog is the most customizable and reliable option when persisting to the filesystem. You can configure there the destination path, the rotation policy and so on. Check this link for more details https://www.krakend.io/docs/logging/#writing-the-log-on-a-file 

Cheers!
