### ISSUE TITLE
Integration test endpoints with auth validators

### ISSUE THREAD

**Issue by MKITConsulting** [krakendio/krakend-ce#531]
Hello,

how does the mocking of the `krakend-integration` command works exactly, is this documented somewhere?

I'd like to integration test an endpoint that is protected by a `auth/validator` with a Token-URL (Keycloak) as well as roles that need to match. Will the `krakend-integration` command try to do a call to my keycloak (I hope not ^^) and how can I build up the headers to enable testing such endpoints? I'd assume that creating a custom JWT token will work out but it did not for me.

Thanks in advance.

**Comment by kpacha** [comment]
@MKITConsulting , please check https://www.krakend.io/docs/enterprise/developer/integration-tests/ for details on how it works.

Also, you can browse the content of https://github.com/krakendio/krakend-ce/tree/master/tests/fixtures to see how the `krakend-integration` is used to harness the krakend binary. In the specs, you'll find 5 tests regarding JWT.

cheers
