### ISSUE TITLE
Gateway removed body after adding input_headers config Krakend

### ISSUE THREAD

**Issue by vanntrong** [krakendio/krakend-ce#534]
**Environment info:**

* KrakenD version: Version: 2.0.5
* System info: Linux 5.10.16.3-microsoft-standard-WSL2 x86_64
* Hardware specs: 4 CPUs, 16GB RAM
* Backend technology: Node
* Additional environment information:

**Describe what are you trying to do**:
I'm trying to extract field from JWT token (JWT.uid) then pass it to the backend service as header[`x-uid`], but the Gateway removed the request body out of the request which is passed to backend service

**Your configuration file**:

```json
{
	"version": 3,
	"endpoints": [{
		"method": "POST",
		"endpoint": "/content/v1/web-contents",
		"output_encoding": "no-op",
		"backend": [{
			"host": ["http://localhost:8082"],
			"url_pattern": "/content/v1/web-contents"
		}],
		"input_headers": ["x-uid"],
		"extra_config": {
			"auth/validator": {
				"alg": "HS512",
				"audience": ["localhost:3000"],
				"issuer": "localhost:8080",
				"roles_key": "roles",
				"roles": [
					"admin"
				],
				"jwk_url": "http://localhost:8081/jwk/symmetric.json",
				"disable_jwk_security": true,
				"propagate_claims": [
					["uid", "x-uid"]
				]
			}
		}
	}]
}
```

**Configuration check output**:
Result of `krakend check -dtc krakend.json --lint` command

```
Parsing configuration file: krakend.json
Global settings
        Name:
        Port: 8080
        Default backend hosts: [http://localhost:8080]
2 global component configuration(s):
- auth/revoker
- security/cors

- POST /content/v1/web-contents
Timeout: 3s
1 endpoint component configuration(s):
- auth/validator
Connecting to 1 backend(s):
        [+] POST /content/v1/web-contents
        Timeout: 3s
        Hosts: [http://localhost:8082]

0 async agent(s):
Syntax OK!
```

**Commands used:**
```
krakend run -d -c krakend.json
```

**Logs:**
```
[GIN] 2022/07/25 - 15:52:34 | 400 |      5.4589ms |             ::1 | POST     "/content/v1/web-contents"
```

**Comment by alombarte** [comment]
The logs show a `400`, which is a bad request, and presumably, this status code comes from the backend itself.

You can see the body that is injected into your backend by replacing your backend with the krakend debug endpoint: https://www.krakend.io/docs/endpoints/debug-endpoint/

Whatever is printed in the krakend logs as post body is what your backend is receiving.

**Comment by kpacha** [comment]
I've added an integration test covering this exact scenario and it works (https://github.com/krakendio/krakend-ce/pull/616).

Check that there are no other headers required by your backend (such as `Content-Type` or `Content-Length`)
