### ISSUE TITLE
What can i do to ensure service is available during the krakend restarting

### ISSUE THREAD

**Issue by yukichenhu** [krakendio/krakend-ce#535]
is there any mechanism just like 'nginx -s reload'?  the configuration file may be modified frequently,i want my backend service is available when i reload the configuration

**Comment by alombarte** [comment]
When deploying new changes, use a technique like blue/green deployment or similar to make the deploy transparent for the user.

This scenario can be automated and is available in Kubernetes and in all major cloud providers. The idea is that you spin up new machines with the latest configuration and then shift the traffic from the old instances to the new ones.

This methodology ensures that there is no downtime when applying changes. On-premises installations can make a similar approach as well, but the implementations depends on the underlying infrastructure.
