### ISSUE TITLE
Can Krakend handle Api Orchestration support concurrent mode and sequential mode in one endpoint (mix mode)

### ISSUE THREAD

**Issue by chchgb** [krakendio/krakend-ce#537]
Is there anyone can help me to build one endpoint with below scenario？

backend A -----> backend B(rely on the result from A) -----> backend D(rely on the result from both B and C)
-----> backend C(rely on the result from A)

much like the mix model in rule engine

similar issues:
https://github.com/krakendio/krakend-ce/issues/176
https://github.com/luraproject/lura/issues/182

sorry, I also raise the same request in luraproject
https://github.com/luraproject/lura/issues/595

**Comment by alombarte** [comment]
Hi @chchgb , you can combine intermediate endpoints (name them something like `/__internal/` for easy identification) and make endpoints consume each other.
