### ISSUE TITLE
Hijack auth/validator’s 401 response via http-client-plugin

### ISSUE THREAD

**Issue by shamanomania** [krakendio/krakend-ce#538]
Hi!
I have some questions about http-client-plugin implementation.
I’d like to redirect to login page, when get 401 status from auth/validator

Similar issue: [Issue #483](https://github.com/krakendio/krakend-ce/issues/483) 

**Environment info:**

* KrakenD version: 2.0.5
* System info: Darwin 20.6.0 x86_64

**Describe what are you trying to do**:

I’d like to realize the next logic:
-> Request to /krakend-protected-endpoint without JWT
-> Hijack auth/validator’s 401 response via the plugin
-> The plugin makes request to Identity Provider (KeyCloak as IDP) with redirect_url (/krakend-protected-endpoint)
-> Opens login page, user logs in, IDP redirects to /krakend-protected-endpoint  with JWT
-> Krakend validates generated JWT and pass it to /krakend-protected-endpoint

Questions:
1. Can I get auth/validator’s result inside the http-client-plugin? What Go-function I should call for?
2. How to replace 401 http code by 303 (with html body) after requesting /kraken-protected-endpoint without JWT? What Go-code is needed?
3. What Go-function can I use to get a krakend endpoint path from config.json (for example “/krakend-protected-endpoint” for futher requesting as redirect_url) ?
4. Can I access input_headers inside the http-client-plugin?

**Comment by alombarte** [comment]
You can do **anything** with a plugin, both with the request and the response. Imagination is the limit :)

The input_headers will let your backend know those headers you are interested in, and your plugin has visibility of it in the `Request`. You can [find examples such as this one](https://www.eventslooped.com/posts/krakend-writing-plugins/), and even this is a server plugin, it shows how modifying req/resp works

Other than that, from the KrakenD team, we do not provide direction on custom code, but actual functionality of the product.

Thanks
