### ISSUE TITLE
CEL Not finding attribute with JWT.

### ISSUE THREAD

**Issue by krishna-kunderu** [krakendio/krakend-ce#540]
Tried Some thing like below as specified in https://www.krakend.io/docs/enterprise/endpoints/common-expression-language-cel/#:~:text=Let%E2%80%99s%20say%20that%20the%20JWT%20token%20the%20user%20sent%20contains%20an%20attribute%20named%20enabled_days%20in%20its%20payload.%20This%20attribute%20lists%20all%20the%20integers%20representing%20which%20days%20the%20resource%20can%20be%20accessed%3A

Failing with error - /:assumeRole/account][CEL] Rejecter #0 failed: no such attribute: id: 1, names: [req_params]
`
....
"endpoint": "/{assumeRole}/account",
    "input_headers":[
      "*"
    ],
    "extra_config": {
      "auth/validator": {
        "alg": "RS256",
        "kid": "somevalue",
        "jwk_url": "http://hostname/auth/realms/realm-name/protocol/openid-connect/certs",
        "disable_jwk_security": true,
        "roles_key_is_nested": true,
        "cache": false,
        "roles_key": "resource_access.clientid.roles",
        "roles": ["1002:account:create", "1003:account:create"]
      },
      "validation/cel": [
          {
              "check_expr": "req_params.AssumeRole in JWT.resource_access.clientid.roles"
          }
      ],
...
`

**Comment by kpacha** [comment]
a cel expression can't contain references to the request (`req_params`) and to the claims contained in a JWT at the same time.

You can export the claim as a header and then use it in the CEL expression
