### ISSUE TITLE
Was 2.0.5 retagged?

### ISSUE THREAD

**Issue by SMillerDev** [krakendio/krakend-ce#541]
**Environment info:**

* KrakenD version: 2.0.5
* System info: package manager
* Hardware specs: N/A
* Backend technology: N/A
* Additional environment information:

**Describe what are you trying to do**:
Trying to rebuild KrakenD in Homebrew

**Your configuration file**:
```json
{}
```

**Configuration check output**:
Result of `krakend check -dtc krakend.json --lint` command

```
```

**Commands used:**
How did you start the software?
```
```

**Logs:**

**Additional comments:**

---

When trying to rebuild KrakenD in Homebrew we noticed that the SHASUM of the 2.0.5 release is now different than before. (see https://github.com/Homebrew/homebrew-core/pull/107225) if this was not done on purpose it could constitute a security issue. If it was done on purpose, the [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do.

**Comment by taik0** [comment]
Hi @SMillerDev you are right, no go code changed, but was a mistake.

2.0.6 is out now so the homebrew build should be available.

**Comment by SMillerDev** [comment]
So it was intentional then?

**Comment by taik0** [comment]
Hi @SMillerDev , no, It was a mistake executing a development script. That problem was corrected and hopefully will not happen again.
