### ISSUE TITLE
 Invalid character in Flexible configuration 

### ISSUE THREAD

**Issue by bellib** [krakendio/krakend-ce#544]
I flowed this doc to implement  flexible configuration  : 
https://www.krakend.io/docs/configuration/flexible-config/#:~:text=The%20Flexible%20Configuration%20component%20is,compiles%20during%20start%2Dup%20time.

But I have this issus : 
```
ERROR parsing the configuration file: '/etc/kt/config/krakend.json': 
invalid character '{' looking for beginning of object key string, offset: 34, row: 2, col: 14
```

And this is krakend.json
```
{
    "version": 3,
    "port": {{ .service.port }},
    "extra_config": {{ marshal .service.extra_config }},
    "host": {{ marshal .service.default_hosts }},
    "endpoints": [
        {{ range $idx, $endpoint := .endpoint.example_group }} 
        {{if $idx}},{{end}}
        {
        "endpoint": "{{ $endpoint.endpoint }}",
        "backend": [
            {
                "url_pattern": "{{ $endpoint.backend }}",
                "extra_config": {
                    {{ include "rate_limit_backend.tmpl" }}
                } 
            }
        ]}
        {{ end }} 
    ]
}
```
I read about this prob ... UTF-8 without bom but same prob ...
### any solution please .

**Comment by alombarte** [comment]
Hi @bellib ,

Add the variable `FC_OUT=result.json` when using the flexible configuration. Then check the `result.json` with an online JSON linter, and IDE, or similar to find out where is the problem.

You probably have additional `{` when including the templates.

**Comment by bellib** [comment]
the program did't output this result.json
