### ISSUE TITLE
ELB Cluster handling in-flight requests/response of Krakend

### ISSUE THREAD

**Issue by krishna-kunderu** [krakendio/krakend-ce#550]
I would like to understand the use case of High availability 

If there is a Kubernetes Cluster with redundancy 3 pods of Krakend instances are running managed by a Load Balancer (ELB).

A request is sent by one POD and before the response comes back that pod goes down, then is the response can be managed by other pods in the Cluster? And if there are sequence of backend calls that has to happen after this response is received, can these be handled by other Pods? My feeling is that this edge scenario cannot by handled unless there is some kind of state is managed. Am I correct in saying this.

**Comment by krishna-kunderu** [comment]
@alombarte, @kpacha Much appreciated, if you have any in-sights on this scenario

**Comment by kpacha** [comment]
No, the instances do not retry requests to backends. Also, they do not know about each other, so if one goes down the in-transit requests and responses will fail and the client should retry
