### ISSUE TITLE
Failed to export to Stackdriver

### ISSUE THREAD

**Issue by jguerreiro-sqsp** [krakendio/krakend-ce#552]
**Environment info:**

* KrakenD version: 2.0.5
* System info: `docker`
* Hardware specs: 1 CPU, 512 MiB of RAM
* Backend technology: Go
* Additional environment information: Deployed to GCP's serverless compute platform Cloud Run

**Describe what are you trying to do**:
I want to export metrics to Google Stackdriver but there is an issue blocking it. 

A log is recorded at server start which hints that Opencensus is correctly configured: `[SERVICE: OpenCensus] Service correctly registered`. However, metrics are not being exported. After a few seconds, numerous error messages start flowing: `Failed to export to Stackdriver: rpc error: code = PermissionDenied desc = Permission monitoring.metricDescriptors.create denied (or the resource may not exist).`.

**Your configuration file**:

```json
{
    "$schema": "https://www.krakend.io/schema/v3.json",
    "version": 3,
    "name": "API Gateway",
    "port": 8080,
    "timeout": "300s",
    "extra_config": {
        "telemetry/opencensus": {
            "sample_rate": 100,
            "reporting_period": 60,
            "enabled_layers": {
                "backend": true,
                "router": true,
                "pipe": true
            },
            "exporters": {
                "stackdriver": {
                    "project_id": "myProjectName",
                    "metrics_prefix": "myProjectName",
                    "default_labels": {
                        "service": "gateway"
                    }
                }
            }
        },
        "telemetry/logging": {
            "level":  "DEBUG",
            "prefix": "[KRAKEND]",
            "syslog": true,
            "stdout": true,
            "format": "logstash"
        },
        "telemetry/metrics": {
            "collection_time": "60s",
            "proxy_disabled": false,
            "router_disabled": false,
            "backend_disabled": false,
            "endpoint_disabled": true,
            "listen_address": ":8090"
        },
        "router": {
            "health_path": "/__health",
            "logger_skip_paths": [
                "/__health"
            ]
        }
    },
    "endpoints": [
        {
            "endpoint": "/api/v1/ping",
            "method": "GET",
            "output_encoding": "no-op",
            "backend": [
                {
                    "host": [ "my.backend.com" ],
                    "url_pattern": "/api/v1/ping"
                }
            ]
        }
    ]
}
```

**Configuration check output**:
Result of `krakend check -dtc krakend.json --lint` command

```
Global settings
        Name: API Gateway
        Port: 8080
4 global component configuration(s):
- router
- telemetry/logging
- telemetry/metrics
- telemetry/opencensus
1 API endpoint(s):
        - GET /api/v1/ping
        Timeout: 5m0s
        Connecting to 1 backend(s):
                [+] GET /api/v1/ping
                Timeout: 5m0s
                Hosts: [http://my.backend.com]

0 async agent(s):
Syntax OK!
```

**Commands used:**
How did you start the software?
```
# My custom image uses devopsfaith/krakend:2.0.5 as base image
# and generates krakend.json file from the flexible configuration 
docker run my-custom-image:tag run -c /etc/krakend/config/krakend.json
```

**Logs:**

- The service account assigned to the Krakend service in GCP is assigned the expected role (Monitoring Metric Writer). 
- The `project_id` property matches the project name in GCP.
- I have tried to explicitly set the `GOOGLE_APPLICATION_CREDENTIALS` variable in Google Cloud Run but to no avail - got the same PermissionDenied errors.

**Additional comments:**

**Comment by taik0** [comment]
Hi @jguerreiro-sqsp Was about to look at this issue next week. Sorry for the delay. I'll keep you posted!

**Comment by taik0** [comment]
Hi @jguerreiro-sqsp 
I've been testing and got to reproduce your same problem.
Take the credentials for your service account and look for the `project_id`, now try to configure the `krakend.json` with that `project_id`. The project name may be different from the project ID, so be sure to use the same (the easiest way is to let the `project_id` in the krakend.json empty and let the exporter use the one configured in the credentials file).

Google also introduced some changes, for instance, the minimum report time for metrics/traces are 60s if you try to send more you will receive an error like:
>One or more points were written more frequently than the maximum sampling period configured for the metric

Also, you need to ensure to set the sample_rate is not 0.

Everything else worked for me, let me know if this helped you to make it work!

**Comment by jguerreiro-sqsp** [comment]
Thank you for looking into this @taik0!

The empty `project_id` has _partially_ solved it.
My local gateway successfully sends metrics to GCP when I set the service account credentials in docker. However, it's not the case when deploying to the GCP project. The permission denied error and any other error messages related to Stackdriver or Opencensus are gone though.

In light of this, we also found that the `metrics_prefix` key, as per the [docs](https://www.krakend.io/docs/telemetry/stackdriver/), should actually be `metric_prefix` as per the [StackdriverConfig](https://github.com/krakendio/krakend-opencensus/blob/f20d95f0879c82c71243b1e479d38f07da716fd5/opencensus.go#L213) struct. This breaks the linter too because the JSON schema validation expects the incorrect `metrics_prefix`. I will file a new bug for this but thought you'd want to know as it could be related.

**Comment by jguerreiro-sqsp** [comment]
Here is the new bug related to `metrics_prefix` - https://github.com/krakendio/krakend-ce/issues/584

**Comment by jguerreiro-sqsp** [comment]
Have some updates @taik0, thank you again for assisting on this one!

Found out that the metrics are being exported! Found them under `VM Instance`, which is a bit unexpected when all other metrics, including from my local Krakend server, are recorded under `Global`. Some strange behaviour about `monitoredresource.Autodetect()`?

Another issue here is that the metrics have no custom prefix as they should - I have `"metric_prefix": "gateway"` right now. Is that an invalid value? 

Fortunately, the labels are all there, which help me crunch some numbers for now.
