### ISSUE TITLE
Krakend does not work with Django for POST requests

### ISSUE THREAD

**Issue by shervintech** [krakendio/krakend-ce#553]
**Environment info:**

* KrakenD version: 2.0.4
* System info: Darwin 21.6.0 arm64
* Backend technology: Django Web Framework

**Describe what are you trying to do**:
I want to run simple Django app that accept POST requests and return POST data as response.
```python
def home(request):
    if request.method == 'POST':
        if 'name' in request.POST:
            name = request.POST['name']
            return HttpResponse(f'Welcome Home {name}!', status=201)
        return HttpResponse('You must send name as form-data', status=400)
    return HttpResponse('Welcome Home!')
```
```
# Run Django server
./manage.py runserver

# Send a request to Django
curl -X POST -F 'name=John' http://127.0.0.1:8000/home

#Response
Welcome Home John!
```
This works flawlessly without Krakend and returns response correctly. But when I use Krakend as API gateway no form-data sending back to my Django backend.

```
# Run Django server
./manage.py runserver

# Run Krakend
krakend -c krakend.json run

# Send a request to Krakend
curl -X POST -F 'name=John' http://127.0.0.1:8080/home

#Response
You must send name as form-data
```

Download [project repo](https://github.com/shervintech/django-krakend-sample)

**Your configuration file**:

```json
{
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "endpoints": [
    {
      "endpoint": "/home",
      "output_encoding": "no-op",
      "method": "POST",
      "backend": [
        {
          "url_pattern": "/home",
          "encoding": "no-op",
          "host": [
            "http://127.0.0.1:8000"
          ]
        }
      ]
    }
  ],
  "extra_config": {
    "telemetry/logging": {
      "level": "DEBUG",
      "syslog": false,
      "stdout": true
    }
  }
}
```

**Configuration check output**:
Result of `krakend check -dtc krakend.json --lint` command

```
Global settings
        Name: 
        Port: 8080
1 global component configuration(s):
- telemetry/logging
1 API endpoint(s):
        - POST /home
        Timeout: 2s
        Connecting to 1 backend(s):
                [+] POST /home
                Timeout: 2s
                Hosts: [http://127.0.0.1:8000]

0 async agent(s):
Syntax OK!
```

**Commands used:**
How did you start the software?
```
krakend -c krakend.json run
```

**Logs:**
 2022/08/20 - 11:38:38.041 ▶ INFO Starting the KrakenD instance
 2022/08/20 - 11:38:38.041 ▶ DEBUG [ENDPOINT: /home] Building the proxy pipe
 2022/08/20 - 11:38:38.041 ▶ DEBUG [BACKEND: /home] Building the backend pipe
 2022/08/20 - 11:38:38.041 ▶ DEBUG [ENDPOINT: /home] Building the http handler
 2022/08/20 - 11:38:38.041 ▶ DEBUG [ENDPOINT: /home][JWTSigner] Signer disabled
 2022/08/20 - 11:38:38.041 ▶ INFO [ENDPOINT: /home][JWTValidator] Validator disabled for this endpoint
 2022/08/20 - 11:38:38.041 ▶ INFO [SERVICE: Gin] Listening on port: 8080
[GIN] 2022/08/20 - 11:38:42 | 400 |    2.566333ms |       127.0.0.1 | POST     "/home"
 2022/08/20 - 11:38:43.042 ▶ DEBUG [SERVICE: Telemetry] Registering usage stats for Cluster ID uAIFJEAwGqv5c97v+T1icKxY2iZIUcC0Nud0+wT+kEs=

#**Additional comments:**

**Comment by moritzploss-k** [comment]
change your `krakend` config so that it makes a `POST` request to your backend. Currently it makes a `GET` request since you did not specify `method` explicitly:

```json
"backend": [
    {
        "url_pattern": "/home",
        "encoding": "no-op",
        "method": "POST",
        "host": [
        "http://127.0.0.1:8000"
        ]
    }
]
```

**Comment by taik0** [comment]
Hi @shervintech 
This may come late, but I would say that your backend is not receiving the required headers since your `input_headers` configuration is empty.

Try setting `input_headers` (I think adding the `Content-Length` should be enough to start) and try again.

**Comment by shervintech** [comment]
Hi @taik0 
Yes it works.
