### ISSUE TITLE
[Kubernetes/Ingress Controller] SSL_do_handshake() failed. 

### ISSUE THREAD

**Issue by droslean** [krakendio/krakend-ce#559]
Is there any ingress configuration that I can use in order to make krakend accessible deployed in Kubernetes?

P.S Nothing on https://www.krakend.io/blog/krakend-on-kubernetes/

/cc @kpacha

**Comment by droslean** [comment]
@kpacha friendly reminder.

**Comment by alombarte** [comment]
Hi @droslean 

Have you gone through the links in the getting started? There are at least 2 kubernetes examples:
https://www.krakend.io/docs/overview/guides/

How is the body of this issue related to its title?

**Comment by droslean** [comment]
@alombarte Disabling TLS in krakend, solved my problem.
