### ISSUE TITLE
Asynchronous Health Checks on *Backend* Hosts

### ISSUE THREAD

**Issue by johhue** [krakendio/krakend-ce#562]
Hello, can Krakend monitor backend hosts to ensure they are healthy ASYNCHRONOUSLY before an attempt is made?

Say my hosts is like this: 

      "backend": [
          {
              "host": ["http://hostA:12345","http://hostB:12345","http://hostC:12345","hostD:12345"],
         ...

And hostD is DOWN for whatever reason (not pingable, not resolvable, tcp half open not good, or fails some health check).

I do not want traffic to even be attempted at hostD. I see with circuit breaker AFTER it fails it may mark it as bad.

Traffic to the other hosts should continue.

Is there such a feature to do health checks PROACTIVELY?

**Comment by alombarte** [comment]
Hi @johhue, this is not supported
