### ISSUE TITLE
Remove [SERVICE: Logging] Unable to create the logger: getting the extra config for the krakend-gologging module

### ISSUE THREAD

**Issue by alombarte** [krakendio/krakend-ce#565]
We should change the policy of logging errors as it works in the rest of the components:
https://github.com/krakendio/krakend-ce/blob/master/executor.go#L302

The error shouldn't display unless it is an error. The absence of configuration is not an error.

**Comment by taik0** [comment]
Fixed in https://github.com/krakendio/krakend-ce/commit/2270a4531693af280cf6322320911d3a30c5f1be
