### ISSUE TITLE
Include multiple http-client plugins

### ISSUE THREAD

**Issue by granadytos** [krakendio/krakend-ce#570]
Hi team,

Is there any way to include more than one plugin from http-client (ex: add in one endpoint wildcar, no-redirect and http-logger)
we are using Enterprise edition and we want to configure them :
Example

![image](https://user-images.githubusercontent.com/4931321/189715792-0dbe657c-e5b3-45bc-b330-9c3677a943e5.png)

Thanks

**Comment by alombarte** [comment]
Hello Erick, please get in touch with support@krakend.io from your company domain for Enterprise questions.
Thanks
