### ISSUE TITLE
plugin.Open("plugin/krakend-client-example"): plugin was built with a different version of package runtime

### ISSUE THREAD

**Issue by deven1009** [krakendio/krakend-ce#576]
**Describe what are you trying to do**
I have a gateway with 1 sample plugin which mentioned in krakend documentation(https://www.krakend.io/docs/extending/http-client-plugins/). so, when I tried to run krakend using docker file. Docker container doesn't able to include plugin.

**Your configuration file** 
The content of your krakend.json. When using the flexible configuration option, the computed file can be generated using FC_OUT=out.json
`{
	"version": 3,
	"name": "my-gateway",
	"port": 8080,
	"plugin": {
		"pattern": ".so",
		"folder": "./plugin/"
	},
	"cache_ttl": "3600s",
	"timeout": "30s",
	"host": [],
	"extra_config": {
		"security/cors": {
			"allow_headers": [
				"Origin",
				"Authorization",
				"Content-Type",
				"Content-Length",
				"Cookie"
			],
			"allow_methods": [
				"POST",
				"GET"
			],
			"allow_origins": [],
			"expose_headers": [
				"Content-Length"
			],
			"max_age": "12h"
		},
		"telemetry/logging": {
			"level": "DEBUG",
			"prefix": "[KRAKEND]",
			"stdout": true,
			"syslog": false
		},
		"telemetry/metrics": {
			"backend_disabled": false,
			"collection_time": "60s",
			"endpoint_disabled": false,
			"listen_address": "8090",
			"proxy_disabled": false,
			"router_disabled": false
		}
	},
	"endpoints": [
		{
			"endpoint": "/test/{id}",
			"backend": [
				{
					"host": [
						"http://localhost:8080"
					],
					"url_pattern": "/__debug/{id}",
					"extra_config": {
						"plugin/http-client": {
							"name": "krakend-client-example",
							"krakend-client-example": {
								"path": "/__debug/hijack-me"
							}
						}
					}
				}
			]
		}
	]
}`
go.mod
`module krakend-client-example

go 1.17
`
**Command Used**
DockerFile
`FROM golang:1.17-alpine3.15 as goplugin
WORKDIR /app
COPY /plugins/krakend-client-example/go.mod .
COPY /plugins/krakend-client-example/*.go  plugin/

RUN apk add make gcc musl-dev
RUN go build -buildmode=plugin -o ./plugin/krakend-client-example.so ./plugin/main.go

FROM devopsfaith/krakend:2.0.5 as builder

COPY krakend.json .
COPY config .

RUN FC_ENABLE=1 \
    FC_OUT=/tmp/krakend.json \
    FC_PARTIALS="/etc/krakend/partials" \
    FC_SETTINGS="/etc/krakend/settings" \
    FC_TEMPLATES="/etc/krakend/templates" \
    krakend check -d -t -c krakend.json

RUN krakend check -c /tmp/krakend.json

FROM devopsfaith/krakend:2.0.5

USER root
COPY --from=builder --chown=root /tmp/krakend.json /etc/krakend
COPY --from=goplugin /app/plugin  /etc/krakend/plugin/

WORKDIR /etc/krakend

CMD [ "run", "-dc", "/etc/krakend/krakend.json" ]
`
**Logs**
Docker logs 
`Parsing configuration file: /etc/krakend/krakend.json
[KRAKEND] 2022/09/19 - 10:09:24.966 ▶ DEBUG [SERVICE: Plugin Loader] Starting loading process
[KRAKEND] 2022/09/19 - 10:09:24.973 ▶ DEBUG [SERVICE: Executor Plugin] plugin #0 (plugin/krakend-client-example.so): plugin.Open("plugin/krakend-client-example"): plugin was built with a different version of package runtime
[KRAKEND] 2022/09/19 - 10:09:24.974 ▶ DEBUG [SERVICE: Handler Plugin] plugin #0 (plugin/krakend-client-example.so): plugin.Open("plugin/krakend-client-example.so"): plugin was built with a different version of package runtime (previous failure)
[KRAKEND] 2022/09/19 - 10:09:24.974 ▶ DEBUG [SERVICE: Modifier Plugin] plugin #0 (plugin/krakend-client-example.so): plugin.Open("plugin/krakend-client-example.so"): plugin was built with a different version of package runtime (previous failure)
[KRAKEND] 2022/09/19 - 10:09:24.974 ▶ DEBUG [SERVICE: Plugin Loader] Loading process completed
[KRAKEND] 2022/09/19 - 10:09:24.974 ▶ DEBUG [SERVICE: Stats] The endpoint /__stats is now available on 8090
[KRAKEND] 2022/09/19 - 10:09:24.974 ▶ DEBUG [SERVICE: Gin] Debug enabled
[KRAKEND] 2022/09/19 - 10:09:24.974 ▶ INFO Starting the KrakenD instance
[KRAKEND] 2022/09/19 - 10:09:24.975 ▶ ERROR [SERVICE: Stats] listen tcp: address 8090: missing port in address
`

Please let me know what I am doing wrong in this part.

**Comment by taik0** [comment]
Hi @deven1009,

I think the problem is that you are using the latest available golang version (`golang:1.17-alpine3.15`) which is different from the one used to build KrakenD.

You can check the required Go and Alpine versions here:
https://github.com/krakendio/krakend-ce/blob/v2.0.5/Makefile#L22

You can also use the KrakenD command `check-plugin`, that will tell you which versions do you need for that specific binary.

In the next version we are going to include a command (`krakend version`) that dumps the Golang and Glibc versions directly.

**Comment by deven1009** [comment]
Thanks @taik0 for quick response.
It is working fine with `golang:1.17.11-alpine3.15`
Yeah it is very useful if we can check compatible version of Golang and Glibc directly from `krakend version` command.

**Comment by deven1009** [comment]
Hi @taik0,

I have one more doubt in custom plugin is there any provision to include go plugin which is triggered on the endpoint level not on the backend. Like I want to implement Role based access for krakend endpoint. So that only authorized user access krakend API.  I have one external service API which check is user authorized for endpoint according to their email and scope parameter.
Can It be integrated with this external API with krakend API which trigger after JWT validation? if the response is true then its only allow to execute backend calls else return forbidden response.
Please refer this usec
![Usecase](https://user-images.githubusercontent.com/113898395/191195705-1c04181f-5660-48a5-9a61-7fe7c050af78.png)
ase:

**Comment by taik0** [comment]
Hi @deven1009 
Let's move this conversation to our slack channel so the issue comments are only related to the issue title.

Thank you!
