### ISSUE TITLE
Wildcard in path

### ISSUE THREAD

**Issue by Phelan164** [krakendio/krakend-ce#578]
I got an error when trying wildcard in a path 

`panic: only one wildcard per path segment is allowed, has: '*}:rename' in path '/v1alpha/{name=models/*}:rename'`

then I tried to replace `:` to `/`, and got another error

`panic: catch-all routes are only allowed at the end of the path in path '/v1alpha/{name=models/*}/rename'`

Question:
is it possible to make path like `/v1alpha/{name=models/*}:rename` or `/v1alpha/{name=models/*}/rename`?

**Comment by kpacha** [comment]
That endpoint pattern is malformed:

- krakend doesn't support wildcards
- variables are defined just by name
- `:` is a reserved char

try `/v1alpha/{models}/rename`
