### ISSUE TITLE
ARM64 Docker images

### ISSUE THREAD

**Issue by solamarpreet** [krakendio/krakend-ce#579]
Hello. Would be a good idea to provide ARM64 images in Docker Hub. Its a simple configuration change in the build process. Ty

**Comment by alombarte** [comment]
Thanks, this is something we will do

**Comment by taik0** [comment]
Hi @solamarpreet

KrakenD now supports ARM64, both Docker and binaries, since the 2.1.3 version.

In the end, it wasn't a simple change 😅
