### ISSUE TITLE
How to handle secret environment-specific variables?

### ISSUE THREAD

**Issue by vyobukhov** [krakendio/krakend-ce#586]
**Environment info:**

* KrakenD version: latest
* System info: docker / k8s

**Describe what are you trying to do**:
Hi guys, I'm trying to figure out how to handle passing env variables to krakend. Right now there are three solutions:
- top-level `KRAKEN_` variables
- `{{env }}` template helper
- env-specific FC_SETTINGS file

But all those solutions are build-time only. What about runtime variables and especially secret runtime variable? For example:
- different InfluxDB in dev and production environments
- some internal service API key / password in dev/prod environments that should not be hardcoded into the built image

Any suggestions?

**Comment by alombarte** [comment]
Hi @vyobukhov,

KrakenD has integration with several vault systems (e.g.: `hashivault://keyID`) but it works only for the local secrets of the JWK retrieval. For the influx password, there is no such integration. 

As you have pointed out, either you pass it as a  `settings/influx.json` or env during build time, or you inject with an environment file using flexible configuration in the runtime.

So a `INFLUX_DB_PASSWORD=123 FC_ENABLE=1 krakend run ...` is going to work.

I am guessing that your question comes from the fact that you are generating an immutable image with a final unique krakend.json after a previous step of flexible configuration checking and compilation. In a case like this, I can think of 3 options:

1) You execute the flexible config on runtime, injecting the env var with the pass
2) You generate an intermediate krakend.json file where the only flexible configuration pending to do is the password and launch it with the aforementioned `INFLUX_DB_PASSWORD=123 FC_ENABLE=1 krakend run ...` 
3) You create an entry point for doing just that.

For the entry point I am going to set an example of what I am mean. Let's imagine that we have the following `krakend.json` **after** compiling the flexible configuration:

```
{
    "version": 3,
    "some_extra_config_for_influxdb": {
        "password": "___INFLUX_DB_PASSWORD___"
    }
}
```
The `___PLACEHOLDERS___` mark those variables needing env var replacement during runtime. Then you write a simple script like the following: https://gist.github.com/alombarte/794fb5db18cb27ebbfca88626f86d5ba

The script takes cares of replacing the values during time. It's just an example written in bash. If you use this in a container of KrakenD, you will need to tweak it a bit as our base image extends Alpine and does not bring bash, and SH does not bring Indirect variables (e.g: `${!pass}`) and you will need to do evals.
