### ISSUE TITLE
How to pass the whole response body to the next backend?

### ISSUE THREAD

**Issue by timurkhafizov** [krakendio/krakend-ce#587]
**Environment info:**

* KrakenD version: 2.0.6

**Describe what are you trying to do**:
I am trying to build the endpoint which will sequentially go to Service A, get the JSON response, and then pass the whole response to Service B (whether in body using POST or query string using GET). 

I've tried to use Martian, but there is no access to response from the previous backend call; and Lua script (pre-backend), but having the same problem.

Another idea I had is to pass the whole response in query using `service-b/endpoint?data={resp0_data}` but it doesn't pass the `data` attribute as string, but as map.

Am I missing something in documentation which would give access to the response from a previous backend or help to stringify the part of response to be passed as query param?

**Comment by alombarte** [comment]
The current implementation of the sequential is meant to take a specific attribute from the response of A and inject it in the URL of the service B.

The body is not cloned for injection in the next service B, so what you are trying to do is not currently possible
