### ISSUE TITLE
Conditional requests and responses

### ISSUE THREAD

**Issue by Ashish0624** [krakendio/krakend-ce#592]
I'm trying to validate parameters of endpoint like headers and request params using 'check_expr'.

There are multiple checks which krakrend is not validating properly.

My json is : 

{
    "endpoint": "/gateway/testkrkn/{city}",
    "method": "POST",
    "timeout": "2s",
    "extra_config": {
      "validation/cel":[{
        "check_expr":"req_headers['X-Auth'] == ['tested'] || req_headers['X-Auth'] == ['verified'] && req_params.City.startsWith('m') || req_params.City.endsWith('m')"
     }]
    },
    "backend": [
      {
        "url_pattern": "/city/{city}",
        "host": [
          "http://127.0.0.1:8183"
        ],
        "extra_config": {}
      }
    ],
    "output_encoding": "no-op"
}

This validates only the last condition which is <req_params.City.endsWith('m')>.

Can anyone please guide here.

**Comment by alombarte** [comment]
Hi @Ashish0624 ,

If you want to use the input headers than you must declared them.
```
{
"endpoint": "/gateway/testkrkn/{city}",
    "input_headers": ["X-Auth"],
...
},
```
Also, you can use the syntax `"tested" in req_headers['X-Auth']`

**Comment by Ashish0624** [comment]
Hi @alombarte , 

Thanks for responding, I really missed it. That was the main issue.
