### ISSUE TITLE
How can I log the HTTP requests into stdout?

### ISSUE THREAD

**Issue by droslean** [krakendio/krakend-ce#593]
Perhaps there is a better way to debug my application, but I can't find how to configure krakend to display the requests/responses into stdout.

The only configuration I found is https://www.krakend.io/docs/enterprise/backends/http-logger/ but this is dumbing the logs into a file which isn't what I want, and also that plugin is not working at all.

**Comment by alombarte** [comment]
Hi @droslean, the link you have passed is an enterprise plugin. It's not expected to run on the open source edition.

The requests are printed in the access log, unless you are pushing them to InfluxDB or similar log exporting solution. They look like this:
```
[GIN] yyyy/mm/dd - hh:mm:ss | 200 |       4.529µs |      172.17.0.1 | GET      "/user/foo"
[GIN] yyyy/mm/dd - hh:mm:ss | 200 |       3.647µs |      172.17.0.1 | GET      "/category/bar"
```
- The responses are not printed in the logs anywhere

If you want to see more data in the logs both for requests/responses you can write a [Lua script](https://www.krakend.io/docs/endpoints/lua) or a plugin

**Comment by droslean** [comment]
@alombarte Thanks for the response. Well, that plugin is not something we can use even if we go to enterprise.

So I guess this is not supported by krakend, right?

**Comment by droslean** [comment]
@alombarte I and my team are checking krakend to decide if we should go for the enterprise. Can you let me know if this feature is included in the enterprise or are there any plans to have it in the future?

**Comment by alombarte** [comment]
Hi @droslean, KrakenD is very extensible and the feature can be supported with a simple plugin (we can do it) if you need it. Please get in touch with us and reference this issue, we will continue this discussion out of the open source forum.

**Comment by droslean** [comment]
@alombarte I don't think that just showing a deeper level of logs should be done with a Lua script. This is really basic, and krakend should have at least an argument or a configuration to control the debug logs.

**Comment by alombarte** [comment]
Could you provide an example of what you would like to see in the logs?

**Comment by droslean** [comment]
All information about the request will be helpful. Headers, request body etc...

**Comment by alombarte** [comment]
This is exactly what the Enterprise version does. Whether to send it to a file, or to the stdout, is a small detail that can be changed quickly (it is actually on the backlog). And even if you have additional requirements, that can be done too.

On the other side, the open source edition has the `/__debug` endpoint that prints in the logs whatever you send it (it can be used as a backend). I suggested Lua or Go plugins so you can write whatever you want in the logs, with whatever format, and in whatever stage.

KrakenD is not a simple proxy and the request and response has several stages in the flow of KrakenD:
- The request from the client when it hits KrakenD
- The request from KrakenD to the backend(s) after KrakenD filtering rules, validations, middleware, etc.
- The response back from each individual backend to KrakenD
- The resulting merged response after receiving all backend responses
- The response returned to the final user after any middleware
- Not counting any of the 4 different types of plugins you can involve here.

Each of these stages can alter the request and the response, and you could see different request and response on each.
