### ISSUE TITLE
using allow_insecure_connections not allowed by json schema v3

### ISSUE THREAD

**Issue by deprolou** [krakendio/krakend-ce#603]
* KrakenD version: 2.1.0

**Describe the bug**
Trying to use the new introduced flag `allow_insecure_connections` , but the config file check is failing with the below error:

```
krakend check -c /tmp/krakend.json --lint
Parsing configuration file: /tmp/krakend.json
ERROR linting the configuration file:	jsonschema: '' does not validate with https://www.krakend.io/schema/v3.json#/additionalProperties: additionalProperties 'allow_insecure_connections' not allowed
```

Is there anything i might be missing to be able to use this? I'm trying to enable this flag as am communicating with a service over internal IP on a VPC, that does not have a certificate.

**Comment by taik0** [comment]
Hello @deprolou 

This [PR](https://github.com/krakendio/krakend-schema/pull/9) which has the new configuration options is pending.
Will be merged pretty soon.
