### ISSUE TITLE
How to use API Gateway  Krakend gzip? 

### ISSUE THREAD

**Issue by tnh7575** [krakendio/krakend-ce#604]
How to use API Gateway  Krakend gzip?

**Comment by alombarte** [comment]
There are 2 things to have into account regarding gzip:
1) KrakenD DOES NOT gzip the responses back to the client
2) When KrakenD consumes from a backend a gzipped response, it’s transparently decoded. Requests of compression with an `"Accept-Encoding: gzip"` can be disabled with the flag `disable_compression`.

**Comment by tnh7575** [comment]
Thanks for your reply.
Let's check that function.
thank you
