### ISSUE TITLE
Lambda backend: Parameters and headers in request not being passed to lambda event

### ISSUE THREAD

**Issue by aaron-parsons** [krakendio/krakend-ce#612]
Hi. I think I have discovered a bug when running with AWS lambda as the backend set up as suggested here: [https://www.krakend.io/docs/backends/lambda/](url) We are using an AMI acquired through the AWS marketplace running on an ec2 instance. Whilst I can trigger endpoints to run, if I try to pass parameters, or look at the headers, only an empty dictionary is passed as the event. I have read [https://www.krakend.io/docs/endpoints/parameter-forwarding/](url) and have (for now) used wildcards to ensure that all headers and query strings are passed, but still nothing appears in the function itself. I have also tried explicity specifying the parameters in the input_query_strings to no avail.

Can you suggest anything to help trouble shoot this?

Any help you can provide is greatly appreciated.

Aaron

**Environment info:**

* KrakenD version: Run `krakend help | grep Version` and copy the output here
2.1.1
* System info: Run `uname -srm` or write `docker` when using containers
Linux 4.14.294-220.533.amzn2.x86_64 x86_64
* Hardware specs: Number of CPUs, RAM, etc
t2.nano
* Backend technology: Node, PHP, Java, Go, etc.
AWS lambda : python
* Additional environment information:

**Describe the bug**
Parameters and header information is not passed to the lambda backend, even when wildcards are provided to input_headers and input_query_strings.

With a lambda (called "oahu-test-blue-echo") that is just:
```python
def handler(event: dict, context) -> None:
    print(event)
```
when I run:
resp = requests.get("http://<EC2-DNS-NAME>.eu-west-1.compute.amazonaws.com:8080/v1/echo", headers={"some": "thing"}, params={"foo": "bar"})
the backend is triggered, and the lambda runs, but the print statement is just an empty dictionary

**Your configuration file**:

```json
{
    "version": 3,
    "disable_rest": true,
    "name": "My lovely gateway",
    "port": 8080,
    "cache_ttl": "3600s",
    "timeout": "3s",
    "extra_config": {
      "telemetry/logging": {
        "level":  "DEBUG",
        "prefix": "[KRAKEND]",
        "syslog": true,
        "stdout": true
      },
      "telemetry/metrics": {
        "collection_time": "60s",
        "proxy_disabled": false,
        "router_disabled": false,
        "backend_disabled": false,
        "endpoint_disabled": false,
        "listen_address": ":8090"
      },
      "security/cors": {
        "allow_origins": [ "http://192.168.99.100:3000", "http://localhost:3000" ],
        "allow_methods": [ "POST", "GET" ],
        "allow_headers": [ "Origin", "Authorization", "Content-Type" ],
        "expose_headers": [ "Content-Length" ],
        "max_age": "12h"
      }
    },
    "endpoints": [
        {
          "endpoint": "/v1/echo",
          "method": "GET",
          "output_encoding": "json",
          "url_pattern": "/ignore",
          "input_headers": [
            "*"
          ],
          "input_query_strings": [
            "*"
          ],
          "backend": [
            {
              "host": ["ignore"],
              "encoding": "json",
              "sd": "static",
              "method": "GET",
              "extra_config": {
                "backend/lambda": {
                  "function_name": "oahu-test-blue-echo",
                  "region": "eu-west-1",
                  "max_retries": 1
                }
              }
            }
          ]
        }
      ]
}

```

**Commands used**
Software started through an AMI on an ec2 instance. I modified the json file in /etc/krakend/krakend.json and restarted using 
sudo systemctl restart krakend.

**Expected behavior**
I am expecting to see the parameters supplied in the request to be passed through to the lambda.
So in the example of: resp = requests.get("http://<EC2-DNS-NAME>.eu-west-1.compute.amazonaws.com:8080/v1/echo", headers={"some": "thing"}, params={"foo": "bar"})

I'd expect the event to look like:
```python
{"header": {"some":"thing"},
"body": {"foo":"bar"}} 
 ```
or at least something similar to this.

**Logs**
from the syslog
>> krackend:  [GIN] 2022/10/25  - 19:47:34  | 200 |  737.660586.s |    <IPADDRESS>  | GET   "/v1/echo?foo=bar"

the lambda just prints an empty dictionary: "{}"

**Comment by aaron-parsons** [comment]
Hi @kpacha, @taik0 , Sorry to chase on this, I appreciate your time.  I was wondering if you could take a quick look and let me know if this is a bug or if I missed something out on the config? As far as I can tell I've made it look like the documentation, but perhaps you notice something obvious that I have missed? Thanks again.

**Comment by kpacha** [comment]
@aaron-parsons the official lambda SDK does not support sending headers to a lambda function: https://pkg.go.dev/github.com/aws/aws-sdk-go/service/lambda#InvokeInput

**Comment by aaron-parsons** [comment]
Hi @kpacha. Thanks for the response. So that would explain why the headers aren't being passed, but it doesn't explain why the parameters aren't passed in the body. Surely I should be able to pass request parameters to the lambda backend?

**Comment by kpacha** [comment]
notice you did not declare any var at your endpoint pattern, so there is nothing to pass to your lambda function as body. Querystrings are not mandatory, so they are not used as params, just appended to the path.

If you define the endpoint as `"endpoint": "/v1/echo/{foo}"`, requests  to `/v1/echo/bar` should pass the body `{"foo":"bar"}` to your lambda.

**Comment by aaron-parsons** [comment]
Thanks @kpacha. That's the answer I was looking for :-) I'll test it out tomorrow. I'm enjoying using krakenD. Thanks for a good product. Have a good evening.

**Comment by aaron-parsons** [comment]
Hi @kpacha. I had a play with this, this morning and found that if I set backend: [method=POST] whilst "endpoint": "/v1/echo",          "method": "GET" this allows me to pass query string parameters through using curl -d. I'm not sure if that's strictly the best way to do things, but it works for what we need.
