### ISSUE TITLE
How to return 30x(2) statuses to a browser through KrakenD from backend service?

### ISSUE THREAD

**Issue by efureev** [krakendio/krakend-ce#613]
How to return 30x(2) statuses to a browser through KrakenD from backend service?
The route config does not work.. =( 

```
"version": 3,
...
"endpoints": [
  {
      "endpoint": "/v1/auth/{provider}/login",
      "output_encoding": "no-op",
      "backend": [
        {
          "host": ["http://auth:1120"],
          "url_pattern": "/auth/{provider}/login",
          "encoding": "no-op"
        }
      ]
  }
]
```
KrakenD v2.1.2

It need for social auth redirects to open a new tabs in browser.

Now KrakenD returns redirected source

**Comment by alex-pobeditel-2004** [comment]
Hi!  
It's impossible to do in Krakend CE, only in Enterprise Edition :(  
https://www.krakend.io/docs/enterprise/backends/client-redirect/

But here is workaround - when you need to redirect, you can just return HTML response from backend with needed address: https://stackoverflow.com/a/506004

**Comment by SagarKansara98** [comment]
You can also use HTML meta tag for redirection

```
<html>
    <meta http-equiv="refresh" content = "2; url = https://www.google.com/" />
 </html>
```
