### ISSUE TITLE
Use previous backend response data to populate post body using lua

### ISSUE THREAD

**Issue by ledstroem** [krakendio/krakend-ce#614]
Hi, 

I am new to Kraken but quite excited about it. What I am trying to do currently is to have two sequential backends where I would like to use parts of the response from the first backend to populate the body of the second request using Lua. the only issue I am having is to get a hold of the data that I can get via {resp0} if I use it outside the Lua scripts. 

This is the part of the krakend.json where I would like to access the previous response:
` "extra_config": {
            "modifier/lua-backend": {
              "sources": [
                "/etc/krakend/config/lua/enrichRequestBody.lua"
              ],
              "pre": " populate_request_body(request.load(), {resp0});",
              "live": false
            }
      }`

Any input or suggestions would be much appreciated!
Thanks

**Comment by timurkhafizov** [comment]
Hey @ledstroem , I guess, you have the same case as I do here - https://github.com/krakendio/krakend-ce/issues/587 :)
