### ISSUE TITLE
Where is v2.1.2?

### ISSUE THREAD

**Issue by mila-rodriguez-netapp** [krakendio/krakend-ce#617]
**Environment info:** N/A
**Describe what are you trying to do**: Use the "latest" Community version of Krakend.
**Your configuration file**: N/A
**Configuration check output**: N/A
**Commands used:** N/A
**Logs:** N/A

**Additional comments:** The krakend.io site says the latest Community version is v2.1.2, the documentation is for v2.1.2, and there's a v2.1.2 docker image available. However the latest release here is v2.1.1. What is v2.1.2? Where can I find the code and release notes/what's changed for it?

**Comment by alombarte** [comment]
Hello @mila-rodriguez-netapp ,

Thanks for noticing this. The release is now out.
