### ISSUE TITLE
Can you access placeholder values from the request body?

### ISSUE THREAD

**Issue by ajkerr** [krakendio/krakend-ce#619]
The [REST to GraphQL transformation documentation](https://www.krakend.io/docs/backends/graphql/#rest-to-graphql-transformation) contains the following quote:

> KrakenD can use the variables in the body or in the endpoint URL to generate the final GraphQL query that will be sent to the GraphQL server. 

However, I cannot find any examples for accessing variables from the request body, and my experiments indicate that this is not possible. Can placeholders only be used as part of the endpoint URL?

**Comment by alombarte** [comment]
Hello @ajkerr ,
As per the documentation:

> KrakenD can use the variables in the body or in the endpoint URL to generate the final GraphQL query that will be sent to the GraphQL server

KrakenD decodes the body (json) and allows you to use directly any of the values sent.
