### ISSUE TITLE
Installation of krakend-integration fails in Go 1.18 or higher

### ISSUE THREAD

**Issue by jguerreiro-sqsp** [krakendio/krakend-ce#621]
As per the instructions in https://www.krakend.io/docs/developer/integration-tests/, running `go install github.com/krakendio/krakend-ce/v2/cmd/krakend-integration@v2.1.2` should add the binary to my PATH.

However, the package download fails in Go version 1.18 or higher:

```
 » go version
go version go1.19.3 darwin/amd64
 » go install github.com/krakendio/krakend-ce/v2/cmd/krakend-integration@v2.1.2
go: github.com/krakendio/krakend-ce/v2/cmd/krakend-integration@v2.1.2 (in github.com/krakendio/krakend-ce/v2@v2.1.2):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
``` 

As a temporary workaround, running tests in Go 1.17 does the trick, but it would be nice to have version parity between tests and running environments of `krakend-ce`.

**Comment by taik0** [comment]
Hi @jguerreiro-sqsp 

Thank you for reporting this issue.

We are looking into removing the go mod replace directives for the next version.
As a workaround, if you clone the git repository and run the go install from the krakend-integration directory should do the trick.

**Comment by taik0** [comment]
Duplicates #470
