### ISSUE TITLE
Question: "Proxy Protocol" support?

### ISSUE THREAD

**Issue by jandelgado** [krakendio/krakend-ce#624]
When using krakend with TLS enabled behind a load balancer, krakend loses access to the clients ip address, since no `X-Forwarded-For` header can be used in this case.

A common solution to this problem is to use the `proxy protocol` (https://www.haproxy.com/de/blog/haproxy/proxy-protocol/). But to use it, both the load balancer and krakend must be supporting this protocol.

How can the "proxy protocol" be used with krakend (on the endpoints side), providing the clients real ip address in an `X-Forwarded-For` header for backend services?

**Comment by alombarte** [comment]
Hi @jandelgado ,

The proxy protocol is a feature developed on the enterprise edition and included in the next release. There are no current plans on making it open source. I am closing the issue since it won't apply to the community edition.

Thanks

**Comment by jandelgado** [comment]
Sad to hear that. 

For anyone needing the feature in the community edition: I successfully put a HAProxy instance (sidecar container) in front of krakend, doing the TLS termination and providing the "proxy protocol" feature to get access to the client ip address. When using mTLS for authentication, this approach also easily allows to extract information (like e.g. the CN) from the client certificate and passing this information in HTTP headers downstream.
