### ISSUE TITLE
Question/Help - Token validation failing with multiple audiences.

### ISSUE THREAD

**Issue by samstride** [krakendio/krakend-ce#625]
**Environment info:**

* KrakenD version: 2.1.2

**Describe what are you trying to do**:

Configuring `auth/validator`

**Your configuration file**:

```json
"auth/validator": {
    "jwk_url": "https://auth.something.io/.well-known/jwks.json",
    "alg": "RS256",
    "cache": true,
    "cache_duration": 15,
    "audience": [
        "https://audience1.something.io",
        "https://audience2.something.io",
    ],
    "issuer": "https://auth.something.io"
}
```

**Question**

With the above config which has 2 values in audience array, if an access token only has `https://audience1.something.io` , then I get a 401 unauthorized.

If, I change the config to only have:

```json
"audience": [
        "https://audience1.something.io"
    ]
```

Then it works.

Is this expected behaviour?

Docs at [krakend.io](https://www.krakend.io/docs/authorization/jwt-validation/) say this:

```
audience - Reject tokens that do not contain an audience from the list.
```

Which to me means that it does not have to be a full match. As long as the audience in the token matches at least 1 item in the array, it should be ok.

Thanks in advance.

**Comment by alombarte** [comment]
Hi @samstride , you are right.

The documentation is inaccurate. I have changed it and it will be published soon.
