### ISSUE TITLE
How to change the http status of an endpoint?

### ISSUE THREAD

**Issue by pooding55** [krakendio/krakend-ce#627]
Hello. I have a need to change the status that endpoit returns. KrakenD almost always returns 200 or 500

I'm trying to do this in LUA using **r:statusCode(404)** but krakenD's response doesn't change.

I can change the endpoint response using **r:data():set('key', 'value')**, but the status doesn't work.

Tell me, please, am I doing something wrong or is there no such possibility?

**Comment by sharpknifeedge** [comment]
Hi! I solved this issue, in two different ways. 
1. Use NO OP mode, in the configuration of your Kraken. Then KrakenD won't do the data manipulation.
2. In case you were not succeeded, I modified the Lura project itself, so all the status codes can be received intact.

**Comment by pooding55** [comment]
@sharpknifeedge 
Hi!
But no-op does not allow using responseData:set, for example.

If it's not difficult for you, you can show a code example of how you implemented it. I will be very grateful to you!

**Comment by sharpknifeedge** [comment]
@pooding55 And the name is something funny. Don't mind the name :D

**Comment by pooding55** [comment]
In the end I did this:

In endpoint config:

`"output_encoding": "no-op",
      "extra_config": {
        "modifier/lua-proxy": {
          "allow_open_libs": true,
          "sources": [
              "/etc/krakend/lua-scripts/myResponseFormatter.lua"
           ]},
          "post": "error_response_formatter();"
        }
      },`
      
And script

`function error_response_formatter( resp )
    local api_response = response.load();
    local api_response_code = api_response:statusCode();

    if api_response_code ~= 200 then
        local error_message = api_response:body():match('.+"message"%s?: "([^"]+)"')
        api_response:statusCode(api_response_code);
        api_response:body('{"errors": [{"custom_error_message": "' .. error_message .. '"}]}');
    end
end

`

I know that working with json through regex looks terrible, but this is the way.
