### ISSUE TITLE
How to pass Elastic Search Query to the body of the krakend endpoints?

### ISSUE THREAD

**Issue by rohit-raje-786** [krakendio/krakend-ce#629]
**Environment info:**

* KrakenD version: Run `krakend help | grep Version` and copy the output here
* System info: Run `uname -srm` or write `docker` when using containers
* Hardware specs: Number of CPUs, RAM, etc
* Backend technology: Node, PHP, Java, Go, etc.
* Additional environment information:

**Describe what are you trying to do**:
A clear and concise description of what you want to do and what is the expected result.
I wanted to retrieve the results from elastic search via krakend,I've written the query which I've encoded in base64 and passing that under body.Modifier but getting the response as 500.
**Your configuration file**:

```json
{
  "version": 3,
 "endpoints": [
 {
      "endpoint": "/first20projects",
      "method": "GET",
      "output_encoding": "json",
      "backend": [
        {
          "host": ["http://sample.com"],
          "url_pattern": "/my-projects/_search",
          "extra_config": {
            "modifier/martian": {
              "fifo.Group": {
                "scope": ["request", "response"],
                "modifiers": [
                  {
                    "body.Modifier": {
                      "scope": ["request"],
                      "body": "ewogICAgImZyb20iOjAsCiAgICAic2l6ZSI6MjAsCiAgICAicXVlcnkiOiB7CiAgICAibWF0Y2hfYWxsIjp7fQogIH0KfQ=="
                    }
                  }
}
}
},
"encoding": "json",
          "sd": "static",
          "method": "GET"
}
]
}

```

**Configuration check output**:
Result of `krakend check -dtc krakend.json --lint` command

```
Output of the linter here.
```

**Commands used:**
How did you start the software?
```
#Example:
krakend run -d -c krakend.json

# Or maybe...
docker run --rm -it -v $PWD:/etc/krakend \
        -e FC_ENABLE=1 \
        -e FC_SETTINGS="/etc/krakend/config/settings" \
        -e FC_PARTIALS="/etc/krakend/config/partials" \
        -e FC_OUT=out.json \
        devopsfaith/krakend \
        run -c /etc/krakend/config/krakend.json -d
```

**Logs:**
Logs you saw in the console and debugging information
2022/11/17 11:06:29 KRAKEND ERROR: [ENDPOINT: /projectsDetails/:id] invalid status code
[GIN] 2022/11/17 - 11:06:29 | 500 |  224.862542ms |      172.17.0.1 | GET      "/projectsDetails/first20projects"

**Additional comments:**

**Comment by taik0** [comment]
Have you checked the elasticsearch logs to see why it hasn't returned a 200 or a 201 status code?
You can also add a backend using the debug endpoint to see what elasticsearch is receiving.
```
            "backend": [
                {
                    "url_pattern": "/__debug/anything",
                    "host": [ "http://krakend:krakend_port" ]
                }
...
```

**Comment by rohit-raje-786** [comment]
@taik0 yeah I did the same thing the content which I am passing inside body.Modifier is displaying in the logs by the above method,but when I'm trying to put the URL of my backend server inside host, I'm not receiving the body at my backend server.

**Comment by rohit-raje-786** [comment]
`{
      "endpoint": "/first",
      "method": "GET",
      "backend": [
        {
          "host": ["http://my-backend-server.com"],
          "url_pattern": "/api/elasticsearch",
          "extra_config": {
            "modifier/martian": {
              "fifo.Group": {
                "scope": ["request", "response"],
                "modifiers": [
                  {
                    "body.Modifier": {
                      "scope": ["request"],
                      "body": "eyJtc2ciOiJ5b3Ugcm9jayEifQ=="
                    }
                  },
                  {
                    "header.Modifier": {
                      "scope": ["request"],
                      "name": "Authorization",
                      "value": "Basic eyJtc2ciOiJ5b3Ugcm9jayEifQ=="
                    }
                  }
                ]
              }
            }
          },
          "method": "GET"
        }
      ],
      "headers_to_pass": ["Content-Length"]
    },`
