### ISSUE TITLE
Non existing Path - Panic error - 502 instead of 404

### ISSUE THREAD

**Issue by elvince** [krakendio/krakend-ce#632]
**Environment info:**

* KrakenD version: 2.1.2
* System info: docker

**Describe the bug**
If you call a path that is not set inside your configuration we got a 502 bad gateway answer instead of 404.

**Expected behavior**
Answer should be 404 as previous versions.

**Logs**
` http: panic serving 10.0.0.2:35440: invalid node type`

**Comment by kpacha** [comment]
Yes, it is a known bug of the internal router. There is an unreleased fix related to the report (https://github.com/gin-gonic/gin/issues/2959) and a workaround: set `"disable_redirect_fixed_path": true` (https://www.krakend.io/docs/service-settings/router-options/#disable_redirect_fixed_path)
