### ISSUE TITLE
Rate limits per minute or per hour configuration

### ISSUE THREAD

**Issue by keshavprasadms** [krakendio/krakend-ce#633]
Hello there, I would like to know how I can configure API rate limits using Krakend on a per hour or per minute or per day basis etc. The current plugin configuration and documentation talks only about per second configuration.

The kong plugin has all these options - https://docs.konghq.com/hub/kong-inc/rate-limiting/

Can we do this on Krakend out of box? Is this feature not requested by anyone else or does this require enterprise subscription?

**Comment by alombarte** [comment]
Hi @keshavprasadms,

KrakenD uses seconds to do the measurement and this is how it's expressed in the documentation. Nevertheless, you can do the calculation and convert it to minutes or hours.

Let's say you want 30 reqs/minute, then you set up a limit 30/60 = 0.5. E.g.:
```
"client_max_rate": 0.5
```
30 reqs/hour would be 30/60/60:
```
"client_max_rate": 0.008333333
```
I could add this into the documentation, so it's more intuitive, but the feature is well-supported.

**Comment by keshavprasadms** [comment]
Thanks @alombarte for the detailed explanation. Definitely please this to the documentation. Its not straightforward for someone to figure this out. 
I was also not aware of the the token bucket and how it works, but after your explanation, its clear. Below is a my sample config to allow 3 requests per minute per client.
```
            "qos/ratelimit/router": {
              "max_rate": 0,
              "client_max_rate": 0.05,
              "strategy": "ip",
              "capacity": 0,
              "client_capacity": 3
            },
```
client_max_rate - 3 requests / 60 seconds = 0.05 (Number of tokens added per second, in this example, every 20 seconds you get one token)
client_capacity - 3 (Maximum number of tokens in the bucker per client. In case of bursts, the client can send 3 requests at once, but once exhausted, they need to wait for bucket to fill, which is 20 seconds for one token)

**Comment by alombarte** [comment]
I am happy that worked for you. You can remove the zero values and default values for a cleaner configuration if you want:

```
            "qos/ratelimit/router": {
              "client_max_rate": 0.05,
              "client_capacity": 3
            },
```

I also edited my comment as the capacity wasn't properly expressed. I am adding this into the documentation on the next update I do.

Thanks
