### ISSUE TITLE
krakend-plugin-builder image tag 2.1.3 not published

### ISSUE THREAD

**Issue by klaude** [krakendio/krakend-ce#635]
Greetings,

I'm using the [devopsfaith/krakend-plugin-builder](https://hub.docker.com/r/devopsfaith/krakend-plugin-builder) image to compile my plugins for compatibility with the containerized version of KrakenD. I see that the `2.1.3` and `2.1.3-alpine` tags aren't published. The `2.1-alpine` tag uses Alpine 3.16.2, while the devopsfaith/krakend:2.1.3 image uses Alpine 3.16.3. This causes my plugins not to load due to a platform mismatch. Can you publish the missing tags? 

I can work in version 2.1.2 for now, but would eventually like to adopt 2.1.3 so we can use the `hide_version_header` config flag. Thanks a lot!

**Comment by taik0** [comment]
Hi @klaude 
We are deprecating de `devopsfaith` namespace, and the "plugin-builder" new name is `krakend/builder`.
I've pushed a copy of the containers to `devopsfaith/krakend-plugin-builder`.
Future versions will only be pushed to `krakend/builder`.

Thanks for reporting!
