### ISSUE TITLE
Using __virtual and __wildcard in Endpoint

### ISSUE THREAD

**Issue by RobertoMachorro** [krakendio/krakend-ce#640]
**Environment info:**

* KrakenD version: Run `krakend help | grep Version` and copy the output here
Docker Image: krakend/krakend-ee:2.1.1
* System info: Run `uname -srm` or write `docker` when using containers
Docker version 20.10.17, build 100c701
* Hardware specs: Number of CPUs, RAM, etc
Kubernetes cluster
* Backend technology: Node, PHP, Java, Go, etc.
Node
* Additional environment information:
Kubernetes cluster
**Describe what are you trying to do**:
What is the proper way of configuring an endpoint that will use both the Virtual Hosts and Wildcard plugins?
In particular, how do you define the endpoint? Do you place both reserved endpoints to the path? Example:
```json
{
  "endpoint": "/__wildcard/__virtual/foo.com/bar/*",
  ...
}
```
**Your configuration file**:
Nothing yet.
**Configuration check output**:
N/A

**Comment by alombarte** [comment]
I am closing this issue as this is not an open source question and will be handled using the official Enterprise channels.

Thanks
