### ISSUE TITLE
Add CorrelationID to access log

### ISSUE THREAD

**Issue by elvince** [krakendio/krakend-ce#641]
**Describe what are you trying to do**:
Hi,

I'm trying to add CorrelationID header valure to the access log so I can track them in my logs system.

I understand that it may not be something from scratch, but I can find a starting point.
I looked at the logger plug-in, but they just print the message that has been given (and not access log).
Access log seems to be written by GIN router, but I'm not sure.

Thanks for your insights.

**Comment by moritzploss-k** [comment]
Not sure if this is 100 % what you want, but we're logging correlation IDs building by using [this](https://github.com/kivra/krakend-correlationid) correlation ID middleware together with [this](https://github.com/kivra/krakend-metalog) log formatter. As a result, we're logging the correlation ID as part of the request `headers`, i.e., our request logs look like this:

```json
{
  "path": "/user/123",
  "method": "GET",
  "headers": {
    "X-Correlation-Id": "...",
    ...
  },
  ...
}

```

**Comment by elvince** [comment]
Thanks for the answer. We will look at what you shared.

I'm not sure, it's what we want to achieve, but it might help ^^
You are using a new logger with json format and not enriching the access log. that the key difference.

Thanks

**Comment by elvince** [comment]
@alombarte 
Hi, 
is this something you can help us with? I find nothing in the doc on this. 

(happy new year!)

Thanks for your help

**Comment by kpacha** [comment]
I think there are 2 options:
- inject a customized log formatter into the gin router. It will require coding the formatter and compile the project yourself.
- use the opencensus traces at the router level. It will require some configuration and a compatible tracing service (such as jaeger, zipkin, etc). Check the documentation for more details: https://www.krakend.io/docs/telemetry/opencensus/

Cheers
