### ISSUE TITLE
KrakenD in Docker runs into certificate permission error when starting up

### ISSUE THREAD

**Issue by GertjanvanhetHof** [krakendio/krakend-ce#642]
My krakend.json contains the following tls config:
   "tls": {
    "public_key": "/etc/ssl/certs/api.cert.pem",
    "private_key": "/etc/ssl/certs/api.key.pem"
  },

My Dockerfile starts with this:
FROM devopsfaith/krakend:2.0.5
COPY krakend.json /etc/krakend/krakend.json
COPY cert/api.key.pem /etc/ssl/certs
COPY cert/api.cert.pem /etc/ssl/certs

My docker log shows this error:

2022/12/15 21:00:42 KRAKEND INFO: [SERVICE: Gin] Listening on port: 8080
2022/12/15 21:00:42 KRAKEND ERROR: [SERVICE: Gin] open /etc/ssl/certs/api.key.pem: permission denied
2022/12/15 21:00:42 KRAKEND INFO: [SERVICE: Gin] Router execution ended

How to fix this?

**Comment by kpacha** [comment]
check the final filesystem on your docker container. The files must exist and the krakend user must be able to read them.
