### ISSUE TITLE
Exceeding the rate limit should return an HTTP status code of 429 Too many requests

### ISSUE THREAD

**Issue by onurmicoogullari** [krakendio/krakend-ce#645]
Hi,

When applying rate limiting at different levels using extra_config > qos/ratelimit/[X], exceeding the rate limit will result in an HTTP status code of [503 Service Unavailable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503). I think this might cause confusion from a consumer perspective, as it is not clear that the consumer is temporarily blocked because they have reached the limit of allowed requests in a given amount of time.

I think that it would make more sense to respond with an HTTP status code of [429 Too many requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429).

**Comment by kpacha** [comment]
The status code returned by the rate limit depends on where it is placed, which namespace is used and what it is limiting. It can return 503 (when controlling the service/endpoint), 429 (when controlling user quotas) or 500 (when controlling the backend consumption). Check the documentation for more details: https://www.krakend.io/docs/endpoints/rate-limit/ and https://www.krakend.io/docs/backends/rate-limit/
