### ISSUE TITLE
Query parameters are being decoded

### ISSUE THREAD

**Issue by RubyKozel** [krakendio/krakend-ce#648]
**Environment info:**

* KrakenD version: 2.1.2
* System info: docker
* Hardware specs: not relevant
* Backend technology: Node, Go
* Additional environment information:

**Describe what are you trying to do**:

Hi experts,
I'm trying to call a simple URL with endoded query parameters, for example: `/foo?filter=bar%20eq%20baz`
For some reason, the backend receives the query as `filter=bar+eq+baz`, which it considers an error.
I expect that KrakenD will forward the request to the backend with the query parameter as is and not decode it.
as you can see, I tried to use `disable_path_decoding: true` but that didn't do the trick.
Is there another way to disable this decoding?

**Your configuration file**:

```json
{
  "version": 3,
  "port": 8080,
  "name": "Portal Krakend JSON",
  "host": [
    "https://foo.bar.com"
  ],
  "output_encoding": "no-op",
  "timeout": "120s",
  "cache_ttl": "300s",
  "extra_config": {
    "telemetry/logging": {
      "level": "INFO",
      "prefix": "",
      "format": "custom",
      "custom_format": "%{message}",
      "syslog": false,
      "stdout": true
    },
    "security/http": {
      "ssl_proxy_headers": {
        "X-Forwarded-Proto": "https"
      },
      "frame_deny": false,
      "content_type_nosniff": true,
      "browser_xss_filter": true,
      "sts_seconds": "31536000",
      "sts_include_subdomains": true
    },
    "router": {
      "disable_health": true,
      "auto_options": true,
      "disable_path_decoding": true
    }
  },
  "endpoints": [
    {
      "endpoint": "/foo",
      "output_encoding": "no-op",
      "method": "GET",
      "input_headers": [
        "*"
      ],
      "input_query_strings": [
        "*"
      ],
      "backend": [
        {
          "url_pattern": "/foo",
          "encoding": "no-op",
          "method": "GET",
          "host": [
            "https://foo.bar.com"
          ],
          "extra_config": {
            "modifier/martian": {
              "header.Modifier": {
                "name": "x-krakend-request",
                "scope": [
                  "request",
                  "response"
                ],
                "value": "true"
              }
            },
            "qos/http-cache": {}
          }
        }
      ]
    },
]
}
```

**Configuration check output**:
Result of `krakend check -dtc krakend.json --lint` command

```
Output of the linter here.
```

**Commands used:**
How did you start the software?
```
KRAKEND_PORT=$PORT FC_ENABLE=1 FC_SETTINGS="$PWD/settings" FC_TEMPLATES="$PWD/templates" /usr/bin/krakend run -c "$PWD/templates/krakend.tmpl"
```

**Logs:**
Logs you saw in the console and debugging information

**Additional comments:**

**Comment by alombarte** [comment]
Hi @RubyKozel, the flag you are referring to are for parameters in the URL (`{var}` below), not in the query string. The query string has to be calculated by KrakenD as you can compose it using different user input and configuration input together. E.g.:
```
"input_query_strings": ["*"],
"endpoint": "/foo/{var}",
"backend": [
        {
          "url_pattern": "/foo?config_param={var}",
           ...
```

Request `/foo/some?filter=bar%20eq%20baz` would produce backend call `/foo?config_param=some&filter=bar+eq+baz`

**Comment by RubyKozel** [comment]
Hi @alombarte 

In that case, this is not what I'm looking for.
I'm looking for a way to disable the decoding of the query parameter. I expect to have an option to leave the query as is and not decode it
