### ISSUE TITLE
Treat HTTP 202 as success

### ISSUE THREAD

**Issue by Thorndike** [krakendio/krakend-ce#649]
**Version of KrakenD you are using**
2.1.3

**Is your feature request related to a problem? Please describe.**
We are using HTTP 202 in some cases as a result. As it is a 2xx result we expected it to be handled similar to 200 and 201.

**Describe the solution you'd like**
Handle HTTP 202 just like 200 or 201

**Describe alternatives you've considered**

**Additional context**

**Comment by alombarte** [comment]
The `202` status code does not usually return a body. That would make an `encoding=json` to fail when trying to parse the empty response (for aggregation, etc). You can use `no-op` in these cases instead
