### ISSUE TITLE
Upgrade sprig version 

### ISSUE THREAD

**Issue by jguerreiro-sqsp** [krakendio/krakend-ce#656]
**Version of KrakenD you are using**

2.1.4

**Is your feature request related to a problem? Please describe.**

I'm using flexible configuration and have created a template to register endpoints in a DRY way. To access some keys based on an environment variable value, I intended on doing a key lookup for a dict object (using `get $myDict "keyName"` from sprig). However, it looks like Krakend is still using [sprig 2.2](https://github.com/krakendio/krakend-ce/blob/master/go.mod#L72) which doesn't support dict key lookup.

**Describe the solution you'd like**

Bump sprig version to a >=3.0 version.

**Describe alternatives you've considered**

I am currently iterating over each key and doing a string comparison to the environment variable. It does the job but it's harder to read, maintain, and doesn't perform as well.

**Comment by alombarte** [comment]
Sprig will be updated to the latest version on the next release (1-2 weeks)
