### ISSUE TITLE
How get redirect url in response and redirect to url

### ISSUE THREAD

**Issue by esmaily** [krakendio/krakend-ce#658]
I want get redirect url from backend and krakend can redirect to url

**Environment info:**

* KrakenD version: 2.1.4
* System info: Linux 5.15.0-58-generic
* Backend technology: Python ,Go.

```json
{
      "endpoint": "/api/payment/callback",
      "method": "GET",
      "output_encoding": "no-op",
      "input_headers":[  "*"  ],
      "input_query_strings": [  "*" ],
      "backend": [
        {
          "url_pattern": "/payment/callback",
          "encoding": "no-op",
        }
      ]
    },
```
** backend response **:
```json
{

"redirect ":"https://pwa-callback.example.com/callback?transaction=5784553&device=pwa"
}
```

**Comment by alombarte** [comment]
Hi @esmaily, I am not exactly sure what is what you want to do, so I answer for the different scenarios I understand:

1) if you want KrakenD to follow the redirection (not the user) than your backend should return a 302 status code with this URL.
2) If your backend is already returning a 302, but you want to prevent KrakenD from following the redirection, you need the [no-redirect plugin](https://www.krakend.io/docs/enterprise/backends/client-redirect/) (Enterprise)
3) If the callback is within the same host, you could also use [sequential proxy](https://www.krakend.io/docs/endpoints/sequential-proxy/). With something like this:
```
{
    "endpoint": "/api/payment/callback",
    "backend": [
        {
            "host": [
                "https://pwa-callback.example.com"
            ],
            "url_pattern": "/payment/callback"
        },
        {
            "host": [
                "https://pwa-callback.example.com"
            ],
            "@comment2": "resp0_ is the response of previous call. You should remove the host",
            "url_pattern": "/{resp0_redirect}"
        }
    ],
    "extra_config": {
        "proxy": {
            "sequential": true
        }
    }
}
```

**Comment by esmaily** [comment]
I want get `redirect url`  from backend response then redirect to url 


** my app hosts: **
* krakend api host: http://my-krakend-api.com
* backend api host: http://api-example.com
* payment callback   host: http://pwa-callback.example.com

Thank you .

**Comment by esmaily** [comment]
I'm get this error when test your krakend config:
`Error #01: invalid character '<' looking for beginning of value`

**Comment by alombarte** [comment]
`invalid character '<' looking for beginning of value` means that KrakenD is finding a `<` in the backend response in the first place. Probably an `<html` tag instead of JSON content.
Still you haven't answered who is doing the redirection, if KrakenD has to follow it and return the response to the user, or if is the user the one following it.

**Comment by esmaily** [comment]
KrakenD has to follow it and return the response to the user

**Comment by alombarte** [comment]
In that case you have to implement a 302 in the backend pointing to the new URL and KrakenD will follow it and return the response to the user.
