### ISSUE TITLE
Memory Leak in Shadow Backends

### ISSUE THREAD

**Issue by moritzploss-k** [krakendio/krakend-ce#671]
Thanks for making krakend; it's great!

**Environment info:**
```
devopsfaith/krakend:latest@sha256:9f9c768fb0ee57834d290ebbffb5daeb0f0c90c18bc55d3eade61d58f9365bae
```
**Describe the bug**
I'm adding a shadow backend to an endpoint configuration. If the shadow backend returns a `404` response status (probably any non-`2xx` status), krakend's memory footprint increases along with the number of Go routines, and both remain at an increased level until krakend is restarted. I assume this is a bug, or am I missing something?

**Your configuration file**:

```json
{
    "version": 3,
    "name": "Demo Memory Leak",
    "port": 8080,
    "extra_config": {
        "telemetry/logging": {
            "level":  "INFO",
            "prefix": "[KRAKEND]",
            "syslog": false,
            "stdout": true
        },
        "telemetry/opencensus": {
            "exporters": {
                "prometheus": {
                    "port": 8090,
                    "namespace": "krakend"
                }
            }
        }
    },
    "endpoints": [
        {
            "endpoint": "/test",
            "backend": [
                {
                    "host": [ "http://127.0.0.1:8080" ],
                    "url_pattern": "/__health"
                },
                {
                    "host": [ "http://127.0.0.1:8080" ],
                    "url_pattern": "/this/backend/returns/404",
                    "extra_config": {
                        "proxy": {
                            "shadow": true
                        }
                    }
                }
            ]
        }
    ]
}
```

**Commands used**
Start the service:
```bash
docker run \
	-v "${PWD}/krakend.json:/etc/krakend/krakend.json" \
	-p 8080:8080 \
	-p 8090:8090 \
	devopsfaith/krakend:latest
```
Count the number of Go routines:
```bash
curl -s 'http://localhost:8090/metrics' | grep "^go_goroutines " # should be ~20
```

Make 1,000 requests to the `/test` endpoint; keep an eye on the Docker container memory usage while running the command:
```bash
for number in $(seq 1000) ; do \
	curl 'http://localhost:8080/test' ;
done
```

Count the number of Go routines again. It has increased sharply (from ~20 to ~3,000) and never goes back down to the original value. Same for the memory footprint of the Docker container (~20 MB to ~80 MB):
```bash
curl -s 'http://localhost:8090/metrics' | grep "^go_goroutines " # increased to ~3,000
```

**Comment by taik0** [comment]
Hi @moritzploss-k 

Thank you for reporting this bug. 
It should be fixed in https://github.com/luraproject/lura/pull/638 for now.

**Comment by moritzploss-k** [comment]
thanks for the quick fix @taik0 🚀
