### ISSUE TITLE
Is it possible to catch json body when output_encoding is set to "no-op"?

### ISSUE THREAD

**Issue by heiytor** [krakendio/krakend-ce#673]
* KrakenD version: devopsfaith/krakend:latest
* System info: Linux 5.15.0-50-generic x86_64
* Hardware specs: 1 CPU, 1GB ram and 25 SSD
* Backend technology: Node 18
* Additional environment information:

I am trying to capture a 400 status code from my backend (401 and 409 are also sent, for example). However, when I leave it like this:
```json
{
"endpoint": "/cep/{number}",
"method": "GET",
"output_encoding": "json",
"backend": [
{
"url_pattern": "sample",
"encoding": "json",
"sd": "static",
"method": "GET",
"host": [
"sample"
],
"disable_host_sanitize": false
}
],
"input_query_strings": [
"number"
],
"extra_config": {
"qos/ratelimit/router": {
"max_rate": 100,
"client_max_rate": 0,
"strategy": "ip",
"capacity": 0,
"client_capacity": 0
}
},
"concurrent_calls": 3
},
```
A 500 status is raised without any body, which is expected according to the documentation. However, when I set it to "no-op":
```json
{
  "endpoint": "/cep/{number}",
  "method": "GET",
  "output_encoding": "no-op",
  "backend": [
    { 
       "url_pattern": "sample",
       "encoding": "no-op",
       "sd": "static",
       "method": "GET",
       "host": [
         "sample"
       ],
       "disable_host_sanitize": false
    }
  ],
  "input_query_strings": [
    "number"
  ],
  "extra_config": {
    "qos/ratelimit/router": {
    "max_rate": 100,
    "client_max_rate": 0,
    "strategy": "ip",
    "capacity": 0,
    "client_capacity": 0
    }
  },
  "concurrent_calls": 3
},
```
In the terminal, I correctly capture the statuses, however, no body is returned in the request (even the 200 status), and the 400 status returns an error (also without body). Is it possible for the no-op to return a json?

Also important to note that if I change either "encoding" or "output_encoding" to no-op, one at a time, similar errors are raised.

**My configuration file:**
```json
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "name": "...",
  "timeout": "30000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "port": 8080,
  "debug_endpoint": true,
  "endpoints":
```

**Commands used:**
start: docker run -d -t < my-image >

**Logs:**
docker -it:
![image](https://user-images.githubusercontent.com/107213601/217640937-3fb1f7af-3728-41ba-8c68-25f9131375db.png)
no-op success:
![image](https://user-images.githubusercontent.com/107213601/217641422-28b9b4e4-46f0-4f69-90e3-4d09b1ff7f04.png)
no-op error:
![image](https://user-images.githubusercontent.com/107213601/217641360-a5058684-6b7b-43fc-9c1d-b0738c35aa76.png)

**Comment by alombarte** [comment]
Hello @heiytor ,

The `no-op` encoding returns the response of the backend as it is, there is no interpretation, parsing, or manipulation of it (this is why it is called no operation). In the screenshot you have attached, you can see a `"Error: Transferred a partial file"`. This message is not a Krakend message, but your backend's.

Most of the cases the backends require extra headers added in the `input_headers` list to operate properly, such as passing `Accept`, `Content-Type`, etc.

A minor detail I see is that you are passing the query string "number" and also have a parameter in the url `{number}`. Is the backend expecting two different numbers like `/cep/123?number=123`?

**Comment by heiytor** [comment]
> Hello @heiytor ,
> 
> The `no-op` encoding returns the response of the backend as it is, there is no interpretation, parsing, or manipulation of it (this is why it is called no operation). In the screenshot you have attached, you can see a `"Error: Transferred a partial file"`. This message is not a Krakend message, but your backend's.
> 
> Most of the cases the backends require extra headers added in the `input_headers` list to operate properly, such as passing `Accept`, `Content-Type`, etc.
> 
> A minor detail I see is that you are passing the query string "number" and also have a parameter in the url `{number}`. Is the backend expecting two different numbers like `/cep/123?number=123`?

Hi,

I was able to solve the issue by removing the `"concurrent_calls": 3`, or setting it to `1` from the endpoints settings. I also needed to put `Content-Lenght` on the input_headers.

Thanks for your reply!
