### ISSUE TITLE
Handle krakend endpoints permissions with keycloak resources/permissions/policies

### ISSUE THREAD

**Issue by holyris** [krakendio/krakend-ce#674]
Hello, i'm a krakend beginner

Is it possible to handle the access control of krakend endpoints with keycloak RBAC/UBAC ?
Like in this keycloak example : https://github.com/keycloak/keycloak-quickstarts/tree/latest/app-authz-springboot
 
 I know that there is krakend "roles", but we want to go further with keycloak policies, where you can even write JS rules.
 
 Thanks, have a nice week-end

**Comment by alombarte** [comment]
Hi @holyris, our recommendation is that you validate any rules within the gateway, and avoid creating a dependency of each request with your identity provider, or you will have a severe impact in the performance and uptime of your platform.

On KrakenD you can do these "JS rules" with [CEL expressions](https://www.krakend.io/docs/endpoints/common-expression-language-cel/). On KrakenD Enterprise, you will have security policies where you can go crazy with the rules :)

**Comment by holyris** [comment]
@alombarte Thank you for your answer. So I wonder what is the use of the keycloak resource/scope management access ? 
Where can it be used in a microservice architecture ?
