### ISSUE TITLE
check-plugin GLIBC with incompatible OS version

### ISSUE THREAD

**Issue by neoelvishsiao** [krakendio/krakend-ce#676]
https://github.com/krakendio/krakend-ce/blob/31b55b90ed78628cb783726bd4e64d461ba941cb/find_glibc.sh#L15

We're having a problem with check-plugin due to recent updated golang image 1.19.5-alpine3.17 (the builder) is currently using alpine 3.17.2 while krakend image is still at 3.17.1.
```
1 incompatibility(ies) found...
libc
    have: MUSL-1.2.3_(alpine-3.17.2)
    want: MUSL-1.2.3_(alpine-3.17.1)
```

Do we really have to match the exact os version? It would be a little bit diffcult becuase the golang image tag (1.19.5-alpine3.17.1) does not exist.

**Comment by neoelvishsiao** [comment]
The latest golang:1.19.5-alpine3.17 which is 3.17.2 updated two days ago.

Maybe we should use this: https://hub.docker.com/r/devopsfaith/krakend-plugin-builder instead? But it hasn't been updated accordingly after 2.1.3-alpine.

**Comment by taik0** [comment]
Hi @neoelvishsiao 

Use our krakend builder (`krakend/builder` on docker hub) which uses the required versions for everything.
There's always a matching builder container for each krakend version:
`devopsfaith/krakend:2.2.0` -> `krakend/builder:2.2.0`

[devopsfaith/krakend-plugin-builder](https://hub.docker.com/r/devopsfaith/krakend-plugin-builder) is not updated anymore.

**Comment by neoelvishsiao** [comment]
Thank you so much @taik0

You probably has been asked so many times by the guys like us who didn't realize krakend/builder exists becuase it never shows up on our google search.
