### ISSUE TITLE
X-krakend-completed returning as false on successful responses.

### ISSUE THREAD

**Issue by Josef-Gen** [krakendio/krakend-ce#686]
**Environment info:**
KrakenD version: Run CE v2.2.1
* System info: EKS 1.23
* Hardware specs:  5 nodes m6i.xlarge  (4vCPU 16 GB)
* Backend technology: Go and Java

**Describe what are you trying to do:**
We are seeing X-krakend-completed returning as false on successful responses. 
All endpoints are currently using single backends and we are not seeing any errors in the logs. 
It is happening on all endpoints (over 20) across different configuration files as we are using flexible configuration.

**Your configuration file:**

```
Config1.json

{
  "profile": [
    {
      "endpoint": "/test",
      "method": "POST",
      "input_headers": [
        "X-User",
        "Content-Type"
      ],
      "output_encoding": "no-op",
      "extra_config": {
        "auth/validator": {
          "alg": "RS256",
          "scopes": [
            "org_admin"
          ],
          "jwk_url": "URL",
          "cache": true,
          "operation_debug": true,
          "propagate_claims": [
            [
              "sub",
              "X-User"
            ]
          ]
        }
……………..

```
```
Config2.json
{
  "jwk_url": "URL",
  "backends": [
    {
      "backend_host": "Hostname",
      "endpoints": [
        {
          "endpoint": "/documents",
          "method": "GET",
          "input_query_strings": ["documentIds", "withContent"],
          "backend_url_pattern": "/documents",
          "authentication": {
            "disabled": true
          }
        },
        {
          "endpoint": "/documents/active",
          "method": "GET",
          "input_query_strings": ["documentTypeId", "regionId"],
          "backend_url_pattern": "/documents/active",
          "authentication": {
            "disabled": true
          }

………………
```

**Comment by kpacha** [comment]
when using `no-op` pipes, krakend is not able to decide if the response is complete or not. If you use other encodings, the header will reflect the actual value

**Comment by Josef-Gen** [comment]
@kpacha How do we remove this value from the header?

**Comment by gabricar** [comment]
@kpacha Config2 (a different endpoint) does not have no-op and the result also comes back as false.
