### ISSUE TITLE
Flexible config initiated even when FC_ENABLE=0

### ISSUE THREAD

**Issue by tusharsdesai** [krakendio/krakend-ce#688]
**Environment info:**
krakend: 2.2.1

**Describe the bug**
I was trying to debug another issue and wanted to disable flexible config. So, I set FC_ENABLE=0 but let FC_SETTINGS and FC_TEMPLATES be the old values. On startup, krakend tried to access the paths specified by FC_SETTINGS and FC_TEMPLTES, even when FC_ENABLE was set to 0. 

```
01:23:27 $ docker logs docker_apigateway_1 
ERROR parsing the configuration file: loading flexible-config settings:
	- /etc/krakend/settings: open /etc/krakend/settings: no such file or directory
	- /etc/krakend/templates: open /etc/krakend/templates: no such file or directory
01:23:30 $ 
```

**Expected behavior**
FC_SETTINGS and FC_TEMPLATES should be ignored when FC_ENABLE =0.

**Comment by alombarte** [comment]
Hi @tusharsdesai , as clearly states the [documentation of flexible configuration](https://www.krakend.io/docs/configuration/flexible-config/):

> FC_ENABLE=1: Activates Flexible Configuration. You can use 1 or any other value (**but 0 won’t disable it!**). The file passed with the --config flag is the base template and contains the references to any other templates.
