### ISSUE TITLE
Incorrect syntax in "propagate_claims" of "auth_validator" is not picked up by the linter

### ISSUE THREAD

**Issue by ivezakis** [krakendio/krakend-ce#694]
**Environment info:**

* KrakenD version: 2.2.1
* System info: docker

**Describe the bug**
"propagate_claims" in JWT validation settings expects a pair of strings, with the source and target of the header name. If someone forgets to add both of these values, and instead only adds a single one, this is not picked up by the linter, and krakend starts normally.
It only fails when the request reaches KrakenD with an unhelpful Go panic error:

`panic: runtime error: index out of range [1] with length 1`

It took me way too long to figure out what was wrong, so adding this check to the linter would be extremely helpful for any future people like me!

Specifically, the following syntax should be marked as wrong by the linter:

`"propagate_claims": [
                ["sub"]
            ]`

The correct one is the following:

`"propagate_claims": [
                ["sub", "sub"]
            ]`

**Comment by alombarte** [comment]
Thanks @ivezakis for the issue. 

I have added a condition of max and min items to the JSON schema, and it should not be able to lint anymore without a pair of values.
