### ISSUE TITLE
KrakenD 2.2.1 with extra config shadow and post fails.

### ISSUE THREAD

**Issue by casverdi** [krakendio/krakend-ce#698]
I suspect that after fixing https://github.com/krakendio/krakend-ce/issues/671, a new bug popped up in the shadow config where post request fail with the following error:

```
2023/03/27 - 18:02:40.845 ▶ ERROR {"@timestamp":"2023-03-27T18:02:40.845303+00:00","@version":1,"host":"localhost","level":"ERROR","message":"[ENDPOINT: /test] Post \"http://server/test\": http: invalid Read on closed Body","module":"[KRAKEND]"}
[GIN] 2023/03/27 - 18:02:40 | 500 |     979.422µs |      172.23.0.1 | POST     "/test"
Error #01: Post "http://server/test": http: invalid Read on closed Body
```

**Environment info:**

* KrakenD version: Version: 2.2.1
* System info: docker
* Hardware specs: CPUs=16, RAM=32Gb
* Backend technology: Python (FastAPI)
* Additional environment information: See attached docker compose example.

**Describe the bug**
Since version 2.2.1 when **post**ing to a shadowed krakend backend, krakend returns a 500 with `http: invalid Read on closed Body`.
Switching to 2.2.0 fixes the issue.

```json
{
  "version": 3,
  "extra_config": {
    "telemetry/logging": {
      "level": "WARNING",
      "prefix": "[KRAKEND]",
      "syslog": false,
      "stdout": true,
      "format": "default"
    },
    "telemetry/logstash": {
      "enabled": false
    },
    "security/cors": {
      "allow_origins": ["*"],
      "expose_headers": ["Content-Length"],
      "max_age": "12h",
      "allow_methods": ["GET", "POST", "OPTIONS"],
      "allow_headers": ["*"]
    }
  },
  "timeout": "30000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "Test",
  "port": 8080,
  "disable_rest": false,
  "endpoints": [
    {
      "method": "POST",
      "endpoint": "/test",
      "input_headers": ["X-Forwarded-For", "User-Agent"],
      "backend": [
        {
          "method": "POST",
          "url_pattern": "/test",
          "host": "http://server",
          "is_collection": true
        },
        {
          "url_pattern": "/test",
          "host": "http://server_shadow",
          "extra_config": {
            "proxy": {
              "shadow": true
            }
          }
        }
      ]
    }
  ]
}
```
**Commands**
How did you start the software?
```
docker-compose up --build
```

Hit the endpoint with:
```
curl -X POST http://localhost:8080/test --data '{}'
```
**Expected behavior**
The same as in version 2.2.0

**Logs**
NA

**Additional context**
See the attachment. 
[krakend_bug.tar.gz](https://github.com/krakendio/krakend-ce/files/11081871/krakend_bug.tar.gz)

**Comment by kpacha** [comment]
@casverdi the fix linked hasn't been released yet, and that PR fixed also this issue. We are waiting to complete some small other fixes before releasing a 2.2.2 fix version
