### ISSUE TITLE
Krakend 2.2.1 Debian package seems to be built on Alpine

### ISSUE THREAD

**Issue by mila-rodriguez-netapp** [krakendio/krakend-ce#702]
**Environment info:**

* KrakenD version: Run `krakend help | grep Version` and copy the output here  --> 2.2.1
* System info: Run `uname -srm` or write `docker` when using containers --> docker
* Hardware specs: Number of CPUs, RAM, etc
* Backend technology: Node, PHP, Java, Go, etc.
* Additional environment information: 

**Describe the bug**

Krakend 2.2.1 installed via `yum install -y krakend-2.2.1` is pulling in what appears to be an Alpine, not Debian, based image. The same dockerfile with Krakend 2.2.0  (also installed via `yum`) correctly pulled in a Debian-based image. 

It's also reporting that it's built with Go 1.19.5 like 2.2.0 was and not Go 1.20.1 like 2.2.1 is.

**Your configuration file**: not applicable

**Commands used**

```
yum install -y krakend-2.2.1

krakend check-plugin --go 1.20.1 --libc "GLIBC-2.31_(debian-11)" -s /plugins/go.sum:
2 incompatibility(ies) found...
libc
      have: GLIBC-2.31_(debian-11)
      want: MUSL-1.2.3_(alpine-3.17.1)
go
       have: 1.20.1
       want: 1.19.5
```

Contents of the go.sum in this command are irrelevant since it'll fail before it gets to that.

**Expected behavior**
* The expected Go version should be 1.20.1 since that's what 2.2.1 is built with
* The expected libc implementation should be some version of GLIBC with a debian OS

**Logs**
N/A

**Additional context**
I run Krakend in a debian docker image, with a custom plugin. Before running krakend, I use the check-plugin to make sure everything is ok. This is what is now happening after I tried upgrading to 2.2.1:

```
 => ERROR [stage-1 5/7] RUN krakend check-plugin --go 1.20.1 --libc "GLIBC-2.31_(debian-11)" -s /plugins/go.sum                         3.5s
------
 > [stage-1 5/7] RUN krakend check-plugin --go 1.20.1 --libc "GLIBC-2.31_(debian-11)" -s /plugins/go.sum:
#23 3.447 2 incompatibility(ies) found...
#23 3.447 libc
#23 3.447       have: GLIBC-2.31_(debian-11)
#23 3.447       want: MUSL-1.2.3_(alpine-3.17.1)
#23 3.447 go
#23 3.447       have: 1.20.1
#23 3.448       want: 1.19.5
------
executor failed running [/bin/sh -c krakend check-plugin --go 1.20.1 --libc "GLIBC-2.31_(debian-11)" -s /plugins/go.sum]: exit code: 1
```

Krakend is installed via `yum install`:

```
RUN rpm -Uvh https://repo.krakend.io/rpm/krakend-repo-0.2-0.x86_64.rpm \
  && yum install -y krakend-2.2.1
```

If I roll back to 2.2.0, the same `check-plugin` command works (though Go has to be down-rev'd to 1.19.5.) -- eg.

```
 => [stage-1 5/7] RUN krakend check-plugin --go 1.19.5 --libc "GLIBC-2.31_(debian-11)" -s /plugins/go.sum           0.5s
 => [stage-1 6/7] ... (etc) ...
```

I'm forced to conclude that the `yum install` command is pulling in an Alpine-based image, given the libc version being reported by check-plugin

**Comment by taik0** [comment]
Hi @mila-rodriguez-netapp 
You're right; the rpm package was wrong (arm64). A new rpm (`2.2.1-1`) has been published.

Please feel free to re-open if you need to.
