### ISSUE TITLE
setting an endpoints cache_ttl to 0s - value ignored

### ISSUE THREAD

**Issue by shimondoodkin** [krakendio/krakend-ce#707]
setting an endpoints cache_ttl to 0s not working

try setting endpoints cache_ttl to 0s and it passes lint, and takes the default value from service

need a way to specify no cache

**Comment by alombarte** [comment]
Hi @shimondoodkin,

If you set a `cache_ttl` at the service level, you are telling KrakenD that this is the default value when there is no value. Setting in and endpoint to 0 is a no-value. Therefore, KrakenD reuses the service level setting, and this behavior is expected and consistent with all the attributes.

If you need to have endpoints with no cache at all, you can't set a default cache strategy. I would use a different approach: Set in your endpoints the cache_ttl explicitly (you can use flexible configuration using a master value). For instance:

```json
{
    "version": 3,
    "@cache_ttl": "Do not set this",
    "debug_endpoint": true,
    "$schema": "https://www.krakend.io/schema/v3.json",
    "endpoints": [
        {
            "endpoint": "/nocache",
            "cache_ttl": "0s"
        },
        {
            "endpoint": "/cache",
            "cache_ttl": "{{ .defaults.cache_ttl }}"
         }
     ]
}
```

**Comment by shimondoodkin** [comment]
then how to disable cache?

**Comment by alombarte** [comment]
My example above disables the cache TTL for the `/nocache` endpoint, and uses a max-age=0.

DO NOT SET an attribute at the service level and you will be fine.
