### ISSUE TITLE
Should flatmap_filter work if one of the backends returns an error ?

### ISSUE THREAD

**Issue by IvanPiankov** [krakendio/krakend-ce#715]
**Should flatmap_filter work if one of the backends returns an error ?**

There is a config for krakend 2.1.4. When one of the backends fails, flatmap_filter stops agglomerating data. Is it supposed to do that ? And is there any way to make data aggregation continue on error from backend ?

**Comment by alombarte** [comment]
Hi @IvanPiankov , when a backend fails, many of the associated components do not work for this reason (flatmap, CEL, Lua...). It falls in our philosophy of "fail fast".
