### ISSUE TITLE
Need information on grpc plugin configuration using krakend enterprise edition

### ISSUE THREAD

**Issue by Anirban-SCA** [krakendio/krakend-ce#720]
Dear team,

I am looking for details on configuring grpc endpoints using krakend enterprise edition however could not find any details in the krakend site except for the following :

"gRPC
Through KrakenD Enterprise you can connect to your gRPC services by providing us your .proto files. We will generate the necessary plugins for you to make it happen."

Could you please share some details about the krakend.json configuration as well as any intemediate steps to be performed to be able to setup grpc endpoints on krakend enterprise.

Thanks,
Anirban

**Comment by alombarte** [comment]
For KrakenD Enterprise support, please get in touch with your sales representative or the enterprise support channel.

KrakenD issues are for open source only.

Best regards
