### ISSUE TITLE
Configuration of GRPC endpoints on KrakenD Community Edition

### ISSUE THREAD

**Issue by Anirban-SCA** [krakendio/krakend-ce#721]
Dear Team,
Can you please confirm if grpc endpoints can be configured using krakend community edition?

**Comment by alombarte** [comment]
Hi @Anirban-SCA , you can create a plugin to connect to gRPC (or use the Enterprise edition), but you cannot offer gRPC to the client on the community edition without forking and tweaking a lot the source code.
