### ISSUE TITLE
Krakend bloomfilter server log

### ISSUE THREAD

**Issue by Anirban-SCA** [krakendio/krakend-ce#742]
Team,

We wrote go client for bloomfilter. However, when it connects to bloomserver on krakend container through rpc, it does not capture by itself any log if there is any communication established. even with log level "Debug" set on krakend.json. Please suggest how to enable the logs on bloomfilter server hosted on krakend container (port 1234).

**Comment by alombarte** [comment]
The bloomfilter server does not write any logs.

If you want to enable logs in the server, you will need to fork the component
