### ISSUE TITLE
Resolve a sub ressource

### ISSUE THREAD

**Issue by ozee31** [krakendio/krakend-ce#763]
Hi,

I have a question for Krakend.

If an api return this response :

Call `http://myapi.com/user/123`

```
{
  id: "123",
  "name": "Jack",
  "address_id": "abc"
}
```

It's possible to auto resolve address with a call in other api ?
Call `http://otherapi.com/address/abc`

and return a global response like that

```
{
  id: "123",
  "name": "Jack",
  "address": {
     "id": "abc",
     "city": "Paris",
   }
}
```

**Comment by kpacha** [comment]
Yes, you can achieve that by combining the sequential proxy for collecting the results of the second request (https://www.krakend.io/docs/endpoints/sequential-proxy/) and flatmap for final response manipulation (https://www.krakend.io/docs/backends/flatmap/)
